"""Business metadata definitions for all database tables."""

TABLE_META = {
    "dim_OrgType": {
        "display_name": "Organization Types",
        "domain": "Reference",
        "module": "Master Data",
        "description": "Reference table storing organization type classifications such as Dealer, Distributor, Vendor, CNF, Transporter, etc. Used to categorize business partners across sales, purchase, and logistics modules.",
        "search_weight": 4, "priority": "Low",
        "search_keywords": [
            "org type", "organization type", "party type", "partner type",
            "dealer type", "vendor type", "distributor type",
            "type master", "business partner type", "entity type",
            "org category", "organization category", "party category"
        ],
        "common_user_intents": [
            "What types of organizations exist",
            "List all organization types",
            "Show org type codes",
            "Types of business partners",
            "What are the different dealer types",
            "Organization type list with codes"
        ],
        "important_columns": ["orgTypeCode", "orgTypeName", "description"],
        "business_metrics": [],
        "common_filters": ["isActive"],
        "common_groupby": [],
    },
    "dim_PaymentTerm": {
        "display_name": "Payment Terms",
        "domain": "Finance",
        "module": "Master Data",
        "description": "Reference table for payment terms defining due days for invoices. Examples: Net 30, Net 60, Immediate, Credit 90. Used across sales invoicing, purchase invoicing, and accounts receivable/payable.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "payment term", "payment terms", "pay terms", "credit terms",
            "due days", "net days", "payment due", "payment condition",
            "invoice due", "credit period", "payment mode",
            "terms of payment", "payment schedule"
        ],
        "common_user_intents": [
            "What payment terms do we offer",
            "Show all payment terms with due days",
            "Payment terms available",
            "List credit terms",
            "Which payment terms have 30 days due",
            "Payment terms master data"
        ],
        "important_columns": ["termCode", "termName", "dueDays"],
        "business_metrics": ["dueDays"],
        "common_filters": ["isActive"],
        "common_groupby": [],
    },
    "dim_Status": {
        "display_name": "Status Master",
        "domain": "Reference",
        "module": "Master Data",
        "description": "Universal status reference table used across orders, invoices, deliveries, and approvals. Each status has a category (e.g., Order, Invoice, Delivery) and a code/name pair.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "status", "order status", "invoice status", "delivery status",
            "status code", "status name", "status master",
            "approval status", "payment status", "fulfillment status",
            "status category", "status list"
        ],
        "common_user_intents": [
            "What statuses are available",
            "Show all order statuses",
            "List invoice statuses",
            "Status codes and names",
            "What are the delivery statuses",
            "Status categories"
        ],
        "important_columns": ["statusCategory", "statusCode", "statusName"],
        "business_metrics": [],
        "common_filters": ["isActive"],
        "common_groupby": ["statusCategory"],
    },
    "dim_TaxRate": {
        "display_name": "Tax Rates",
        "domain": "Finance",
        "module": "Tax Management",
        "description": "Reference table for GST tax rates including SGST, CGST, IGST percentages. Used in invoicing, purchase orders, and tax calculations across all financial transactions.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "tax rate", "tax rates", "gst rate", "gst rates",
            "sgst", "cgst", "igst", "tax percentage", "tax slab",
            "tax master", "tax code", "tax name",
            "goods and services tax", "tax category"
        ],
        "common_user_intents": [
            "What tax rates are available",
            "Show GST rates",
            "List all tax percentages",
            "Tax rates master",
            "What is the 18% GST rate",
            "SGST CGST rates"
        ],
        "important_columns": ["taxName", "taxRate", "taxType"],
        "business_metrics": ["taxRate", "taxType"],
        "common_filters": ["isActive"],
        "common_groupby": [],
    },
    "dim_UOM": {
        "display_name": "Units of Measurement",
        "domain": "Reference",
        "module": "Master Data",
        "description": "Reference table for units of measurement (KG, MT, Litre, Piece, Box, etc.) used in product definitions, purchase orders, and sales invoices for quantity tracking.",
        "search_weight": 4, "priority": "Medium",
        "search_keywords": [
            "uom", "unit", "units", "unit of measurement",
            "measurement unit", "quantity unit", "weight unit",
            "kilogram", "litre", "piece", "box", "metric ton",
            "uom master", "unit master", "uom list"
        ],
        "common_user_intents": [
            "What units of measurement do we use",
            "Show all UOMs",
            "List measurement units",
            "UOM master data",
            "What UOM codes are available",
            "Units for weight and volume"
        ],
        "important_columns": ["uomCode", "uomName"],
        "business_metrics": [],
        "common_filters": ["isActive"],
        "common_groupby": [],
    },
    "dmn_City": {
        "display_name": "Cities",
        "domain": "Geography",
        "module": "Geography Master",
        "description": "City master table linked to states and countries. Used for organization addresses, warehouse locations, and delivery destinations.",
        "search_weight": 4, "priority": "Medium",
        "search_keywords": [
            "city", "cities", "town", "district", "location",
            "city master", "city list", "city name", "pin code",
            "postal code", "city code", "place", "area",
            "municipality", "metro", "urban", "rural", "locality",
            "city details", "city information", "address city",
            "pincode", "pin", "zip code", "zip"
        ],
        "common_user_intents": [
            "List all cities",
            "Show cities in a state",
            "Which city has pin code X",
            "City master data",
            "All cities in Maharashtra",
            "Cities by country",
            "City wise customers",
            "Delivery cities",
            "City directory"
        ],
        "important_columns": ["cityName", "stateId", "pinCode"],
        "business_metrics": [],
        "common_filters": ["isActive", "stateId"],
        "common_groupby": ["stateId"],
    },
    "dmn_Country": {
        "display_name": "Countries",
        "domain": "Geography",
        "module": "Geography Master",
        "description": "Country reference table. Top level of the geography hierarchy (Country > State > City). Used for address standardization and international trade.",
        "search_weight": 3, "priority": "Low",
        "search_keywords": [
            "country", "countries", "nation", "country master",
            "country list", "country code", "country name",
            "international", "foreign", "domestic", "global",
            "worldwide", "country details", "national",
            "iso country", "country lookup"
        ],
        "common_user_intents": [
            "List all countries",
            "Show country codes",
            "Which countries do we operate in",
            "Country master data",
            "Countries list",
            "Country directory"
        ],
        "important_columns": ["countryCode", "countryName"],
        "business_metrics": [],
        "common_filters": ["isActive"],
        "common_groupby": [],
    },
    "dmn_State": {
        "display_name": "States",
        "domain": "Geography",
        "module": "Geography Master",
        "description": "State reference table linked to countries and cities. Used for GST state codes, delivery routing, and regional sales analysis.",
        "search_weight": 4, "priority": "Medium",
        "search_keywords": [
            "state", "states", "state master", "state list",
            "state code", "state name", "gst state code",
            "region", "province", "territory", "division",
            "state details", "state lookup", "state directory",
            "gst state", "state wise",
            "maharashtra", "gujarat", "rajasthan", "karnataka",
            "tamil nadu", "tamilnadu", "kerala", "andhra pradesh",
            "andhra", "telangana", "uttar pradesh", "delhi",
            "haryana", "punjab", "madhya pradesh", "west bengal",
            "bihar", "odisha", "orissa", "assam", "jharkhand",
            "chhattisgarh", "himachal", "uttarakhand", "goa"
        ],
        "common_user_intents": [
            "List all states",
            "Show states in India",
            "GST state codes",
            "Which states do we serve",
            "States by country",
            "State wise customers",
            "State directory",
            "Employees from Maharashtra",
            "Employees by state",
            "Customers in Gujarat",
            "States that have employees"
        ],
        "important_columns": ["stateCode", "stateName", "countryId"],
        "business_metrics": [],
        "common_filters": ["isActive", "countryId"],
        "common_groupby": ["countryId"],
    },
    "tbl_AccountGroup": {
        "display_name": "Account Groups",
        "domain": "Finance",
        "module": "Accounting",
        "description": "Chart of accounts grouping structure. Parent-child hierarchy for ledgers (e.g., Assets > Current Assets > Cash). Used in journal vouchers and financial reporting.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "account group", "account groups", "ledger group",
            "chart of accounts", "account category", "account head",
            "financial group", "gl group", "general ledger group",
            "account hierarchy", "parent account"
        ],
        "common_user_intents": [
            "Show all account groups",
            "List ledger groups",
            "Chart of accounts structure",
            "Account group hierarchy",
            "Parent child account groups"
        ],
        "important_columns": ["groupName", "parentId", "groupType"],
        "business_metrics": [],
        "common_filters": ["isActive"],
        "common_groupby": ["groupType"],
    },
    "tbl_AccountLedger": {
        "display_name": "Account Ledgers",
        "domain": "Finance",
        "module": "Accounting",
        "description": "Individual account ledgers for tracking financial transactions. Each ledger belongs to an account group and records debits, credits, and balances.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "ledger", "ledgers", "account ledger", "account ledgers",
            "gl", "general ledger", "account head", "account name",
            "financial ledger", "account balance", "debit credit",
            "trial balance", "account code"
        ],
        "common_user_intents": [
            "Show all ledgers",
            "List account heads",
            "Ledger with balance",
            "Show GL codes",
            "Ledger master data",
            "Account ledger list"
        ],
        "important_columns": ["ledgerName", "ledgerCode", "groupId", "openingBalance"],
        "business_metrics": ["openingBalance"],
        "common_filters": ["isActive", "groupId"],
        "common_groupby": ["groupId"],
    },
    "tbl_Attendance": {
        "display_name": "Employee Attendance",
        "domain": "HR",
        "module": "Attendance Management",
        "description": "Daily employee attendance records tracking check-in, check-out, work hours, overtime, and status (present, absent, half-day, leave).",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "attendance", "employee attendance", "check in", "check out",
            "present", "absent", "half day", "work hours", "overtime",
            "daily attendance", "attendance record", "punch in", "punch out",
            "attendance report", "attendance list"
        ],
        "common_user_intents": [
            "Show today's attendance",
            "List absent employees today",
            "Attendance for employee X this month",
            "Overtime hours summary",
            "Monthly attendance report",
            "Present employees today"
        ],
        "important_columns": ["employeeId", "attendanceDate", "checkIn", "checkOut", "status"],
        "business_metrics": [],
        "common_filters": ["employeeId", "attendanceDate", "status"],
        "common_groupby": ["status", "attendanceDate"],
    },
    "tbl_AuditLog": {
        "display_name": "Audit Logs",
        "domain": "System",
        "module": "System Administration",
        "description": "System audit trail recording user actions (create, update, delete) across all modules. Tracks who changed what and when for compliance and debugging.",
        "search_weight": 4, "priority": "Medium",
        "search_keywords": [
            "audit log", "audit trail", "activity log", "change log",
            "user activity", "system log", "action log",
            "audit record", "modification history", "who changed"
        ],
        "common_user_intents": [
            "Show recent audit logs",
            "Who changed invoice X",
            "Audit trail for table Y",
            "Recent system changes",
            "User activity today"
        ],
        "important_columns": ["actionType", "tableName", "recordId"],
        "business_metrics": [],
        "common_filters": ["tableName", "actionType"],
        "common_groupby": ["tableName", "actionType"],
    },
    "tbl_Booking": {
        "display_name": "Bookings",
        "domain": "Sales",
        "module": "Sales Management",
        "description": "Sales booking records capturing customer orders, product details, quantities, pricing, and delivery schedule. Triggers the fulfillment pipeline through invoicing and delivery.",
        "search_weight": 8, "priority": "High",
        "search_keywords": [
            "booking", "bookings", "sales booking", "customer booking",
            "order booking", "booking details", "booking record",
            "booking number", "booking date", "booking status",
            "reservation", "sales order", "demand"
        ],
        "common_user_intents": [
            "Show all bookings",
            "Bookings for customer X",
            "Pending bookings today",
            "Booking details for booking number Y",
            "Total bookings this month",
            "Bookings by date range"
        ],
        "important_columns": ["bookingNo", "bookingDate", "dealerOrgId", "totalAmount", "statusId"],
        "business_metrics": ["bookingQty", "pendingQty", "rate", "totalAmount"],
        "common_filters": ["dealerOrgId", "statusId", "bookingDate"],
        "common_groupby": ["bookingDate", "dealerOrgId", "statusId"],
    },
    "tbl_BookingDelivery": {
        "display_name": "Booking Deliveries",
        "domain": "Sales",
        "module": "Delivery Management",
        "description": "Delivery tracking for bookings. Records delivery date, quantity delivered, vehicle, driver, and delivery status for each booking shipment.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "delivery", "deliveries", "booking delivery", "shipment",
            "dispatch", "delivery details", "delivery status",
            "delivery date", "delivery tracking", "goods delivery",
            "consignment", "delivery note"
        ],
        "common_user_intents": [
            "Show pending deliveries",
            "Deliveries today",
            "Delivery status for booking X",
            "Undelivered shipments",
            "Delivery report this week",
            "Late deliveries"
        ],
        "important_columns": ["bookingId", "deliveryDate", "deliveredQty"],
        "business_metrics": ["deliveredQty"],
        "common_filters": ["bookingId", "deliveryDate"],
        "common_groupby": ["deliveryDate"],
    },
    "tbl_CreditDebitNote": {
        "display_name": "Credit/Debit Notes",
        "domain": "Finance",
        "module": "Accounts Receivable/Payable",
        "description": "Credit notes (returns/allowances) and debit notes (additional charges) issued against invoices. Adjusts outstanding balances for customers and vendors.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "credit note", "debit note", "credit notes", "debit notes",
            "cdn", "dbn", "credit debit note", "adjustment note",
            "return note", "allowance", "rebate", "discount note",
            "note master", "purchase return", "sales return",
            "return records", "return adjustments", "credit debit"
        ],
        "common_user_intents": [
            "Show credit notes this month",
            "Debit notes for vendor X",
            "Pending credit notes",
            "Total credit notes value",
            "Credit notes against invoice Y",
            "Return adjustments"
        ],
        "important_columns": ["noteNo", "noteDate", "noteType", "organizationId", "amount", "invoiceId"],
        "business_metrics": ["amount"],
        "common_filters": ["noteType", "organizationId", "noteDate"],
        "common_groupby": ["noteType"],
    },
    "tbl_Department": {
        "display_name": "Departments",
        "domain": "HR",
        "module": "Organization Structure",
        "description": "Department master listing all organizational departments (Sales, Purchase, HR, Finance, Production, etc.). Each employee belongs to one department.",
        "search_weight": 3, "priority": "Low",
        "search_keywords": [
            "department", "departments", "dept", "dept list",
            "department master", "department name", "organizational unit",
            "team", "division", "section", "unit"
        ],
        "common_user_intents": [
            "List all departments",
            "How many departments",
            "Department master data",
            "Departments in the company",
            "Show department names"
        ],
        "important_columns": ["deptName"],
        "business_metrics": [],
        "common_filters": ["isActive"],
        "common_groupby": [],
    },
    "tbl_Designation": {
        "display_name": "Designations",
        "domain": "HR",
        "module": "Organization Structure",
        "description": "Job designation/title master (Manager, Executive, Director, etc.). Links to employees to define roles and reporting hierarchy.",
        "search_weight": 3, "priority": "Low",
        "search_keywords": [
            "designation", "designations", "job title", "job titles",
            "role", "position", "rank", "grade",
            "designation master", "title master", "job role"
        ],
        "common_user_intents": [
            "List all designations",
            "Show job titles",
            "Designation master data",
            "What designations exist",
            "Designations in HR"
        ],
        "important_columns": ["desigName"],
        "business_metrics": [],
        "common_filters": ["isActive"],
        "common_groupby": [],
    },
    "tbl_DriverMaster": {
        "display_name": "Drivers",
        "domain": "Logistics",
        "module": "Fleet Management",
        "description": "Driver master records with license details, contact information, and vehicle assignments. Used in trip sheets and delivery tracking.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "driver", "drivers", "driver master", "driver list",
            "chauffeur", "transporter driver", "driver name",
            "license number", "driver details", "driver contact",
            "vehicle driver"
        ],
        "common_user_intents": [
            "List all drivers",
            "Show driver details",
            "Driver with license X",
            "Active drivers",
            "Driver contact information",
            "Drivers assigned to vehicles"
        ],
        "important_columns": ["driverName", "licenseNo", "mobileNo"],
        "business_metrics": [],
        "common_filters": ["isActive"],
        "common_groupby": [],
    },
    "tbl_Employee": {
        "display_name": "Employees",
        "domain": "HR",
        "module": "HR Management",
        "description": "Comprehensive employee master storing personal details, contact information, department, designation, reporting manager, employment type, work location, address, and bank/PF/ESI details. Core entity for HR, payroll, and attendance modules.",
        "search_weight": 8, "priority": "High",
        "search_keywords": [
            "employee", "employees", "staff", "staff member", "staff members",
            "worker", "workers", "personnel", "team member", "team members",
            "emp", "emp list", "employee list", "employee master",
            "human resource", "hr", "manpower", "workforce",
            "employee name", "employee code", "emp code",
            "worker details", "employee details", "staff details",
            "headcount", "head count", "man count",
            "new joiners", "joining", "new employee", "recent joiners",
            "who joined", "recently joined"
        ],
        "common_user_intents": [
            "List all employees",
            "Show employee details for X",
            "How many employees in department Y",
            "Employees who joined this year",
            "Total employees",
            "Employee attendance",
            "Employee master data",
            "Active employees list",
            "Employees by designation",
            "Employee contact details",
            "Employees by city",
            "Employees in a city",
            "Employees from Maharashtra",
            "City-wise employee count",
            "Employees by location"
        ],
        "important_columns": ["employeeCode", "firstName", "lastName", "departmentId", "designationId", "reportingToId", "employmentType", "dateOfJoining", "mobileNo", "officialEmail","cityId"],
        "business_metrics": [],
        "common_filters": ["departmentId", "designationId", "isActive", "employmentType","cityId"],
        "common_groupby": ["departmentId", "designationId", "employmentType"],
    },
    "tbl_ErrorLog": {
        "display_name": "Error Logs",
        "domain": "System",
        "module": "System Administration",
        "description": "Application error logging table capturing exception details, stack traces, user context, and timestamps for debugging and monitoring.",
        "search_weight": 3, "priority": "Low",
        "search_keywords": [
            "error log", "error logs", "exception", "exceptions",
            "error", "errors", "bug", "system error",
            "application error", "crash log", "error report",
            "stack trace", "severity", "debug", "timestamp",
            "error details", "error source"
        ],
        "common_user_intents": [
            "Show recent errors",
            "Error log today",
            "What errors occurred",
            "Application exceptions",
            "Error details",
            "Errors by severity",
            "Most common errors",
            "Errors in last 7 days",
            "Errors by source"
        ],
        "important_columns": ["severity", "errorSource", "errorMessage", "stackTrace", "userId", "occurredOn"],
        "business_metrics": [],
        "common_filters": ["severity", "occurredOn", "userId"],
        "common_groupby": ["severity", "errorSource", "occurredOn"],
    },
    "tbl_EwayBill": {
        "display_name": "E-Way Bills",
        "domain": "Compliance",
        "module": "Tax Compliance",
        "description": "E-way bill records for goods movement compliance. Generated for shipments above â‚¹50,000 as per GST rules. Contains transporter, vehicle, and goods details.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "eway bill", "e-way bill", "eway bills", "e-way bills",
            "eway", "ewaybill", "eway bill number", "eway bill details",
            "goods movement", "transport document", "eway generated",
            "eway bill status", "eway bill list"
        ],
        "common_user_intents": [
            "Show eway bills today",
            "Generate eway bill for invoice X",
            "Pending eway bills",
            "Eway bill details",
            "Eway bills by date range",
            "Eway bill status"
        ],
        "important_columns": ["ewayBillNo", "ewayBillDate", "invoiceId"],
        "business_metrics": [],
        "common_filters": ["ewayBillDate", "invoiceId"],
        "common_groupby": ["ewayBillDate"],
    },
    "tbl_GlobalPurchaseRate": {
        "display_name": "Global Purchase Rates",
        "domain": "Pricing",
        "module": "Purchase Pricing",
        "description": "Standard purchase rates for products across vendors. Defines base cost prices used in purchase orders and cost analysis.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "purchase rate", "purchase rates", "buying rate", "cost price",
            "purchase price", "vendor rate", "supplier rate",
            "buying price", "procurement rate", "purchase rate master",
            "global rate", "standard rate"
        ],
        "common_user_intents": [
            "Show purchase rates for product X",
            "Current buying rates",
            "Purchase rate list",
            "Rates from vendor Y",
            "Standard cost prices"
        ],
        "important_columns": ["productId", "purchaseRate"],
        "business_metrics": ["purchaseRate"],
        "common_filters": ["productId"],
        "common_groupby": ["productId"],
    },
    "tbl_GlobalSaleRate": {
        "display_name": "Global Sale Rates",
        "domain": "Pricing",
        "module": "Sales Pricing",
        "description": "Standard sale rates for products across customers/dealers. Defines base selling prices used in sales orders, invoices, and price lists.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "sale rate", "sale rates", "selling rate", "selling price",
            "sale price", "customer rate", "dealer rate", "mrp",
            "list price", "price list", "global rate", "standard rate",
            "product rate", "pricing"
        ],
        "common_user_intents": [
            "Show sale rates for product X",
            "Current selling prices",
            "Sale rate list",
            "Price for customer Y",
            "Standard selling prices"
        ],
        "important_columns": ["productId", "saleRate"],
        "business_metrics": ["saleRate"],
        "common_filters": ["productId"],
        "common_groupby": ["productId"],
    },
    "tbl_GSTReturn": {
        "display_name": "GST Returns",
        "domain": "Compliance",
        "module": "Tax Compliance",
        "description": "GST return filing records tracking GSTR-1, GSTR-3B filings with submission dates, status, and filed amounts. Ensures tax compliance.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "gst return", "gst returns", "gstr", "gstr1", "gstr3b",
            "tax return", "gst filing", "return filing",
            "gst submission", "monthly return", "quarterly return",
            "gst compliance", "tax filing status"
        ],
        "common_user_intents": [
            "Show GST returns filed",
            "Pending GST returns",
            "GSTR-3B status",
            "GST returns this month",
            "Filed GST returns"
        ],
        "important_columns": ["returnType", "returnPeriod", "filingDate", "netGSTPayable"],
        "business_metrics": ["netGSTPayable"],
        "common_filters": ["returnType", "returnPeriod"],
        "common_groupby": ["returnType", "returnPeriod"],
    },
    "tbl_InventoryAdjustment": {
        "display_name": "Inventory Adjustments",
        "domain": "Inventory",
        "module": "Inventory Management",
        "description": "Stock adjustment records for correcting inventory discrepancies. Records reason for adjustment (damage, expiry, theft, correction) and quantity changes.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "inventory adjustment", "stock adjustment", "stock correction",
            "adjustment", "adjustments", "inventory correction",
            "stock variance", "damage write off", "expiry adjustment",
            "physical adjustment", "stock loss", "stock gain"
        ],
        "common_user_intents": [
            "Show recent inventory adjustments",
            "Adjustments for product X",
            "Stock correction records",
            "Damage adjustments this month",
            "Adjustment reasons summary"
        ],
        "important_columns": ["productId", "quantity", "reason", "warehouseId"],
        "business_metrics": ["quantity"],
        "common_filters": ["productId", "warehouseId"],
        "common_groupby": ["reason"],
    },
    "tbl_JournalVoucher": {
        "display_name": "Journal Vouchers",
        "domain": "Finance",
        "module": "Accounting",
        "description": "Journal voucher header recording financial journal entries with debit/credit pairs, narration, and approval status. Core accounting transaction document.",
        "search_weight": 7, "priority": "High",
        "search_keywords": [
            "journal voucher", "journal vouchers", "journal entry",
            "journal entries", "jv", "jv list", "journal book",
            "accounting entry", "debit credit entry", "general journal",
            "journal record", "financial entry"
        ],
        "common_user_intents": [
            "Show journal vouchers this month",
            "Journal entries for account X",
            "Pending journal vouchers",
            "Total journal amount",
            "Journal voucher details",
            "Unapproved journal entries"
        ],
        "important_columns": ["voucherNo", "voucherDate", "totalDebit", "totalCredit", "narration", "statusId"],
        "business_metrics": ["totalDebit", "totalCredit"],
        "common_filters": ["voucherDate", "statusId"],
        "common_groupby": ["voucherDate"],
    },
    "tbl_JournalVoucherDetail": {
        "display_name": "Journal Voucher Details",
        "domain": "Finance",
        "module": "Accounting",
        "description": "Line-level details of journal vouchers. Each row is a debit or credit entry against a specific ledger account within a journal voucher.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "journal detail", "journal line", "journal voucher detail",
            "debit entry", "credit entry", "ledger entry",
            "journal line item", "accounting detail"
        ],
        "common_user_intents": [
            "Show journal lines for voucher X",
            "Debit entries in journal Y",
            "Ledger-wise journal breakdown",
            "Journal detail by account"
        ],
        "important_columns": ["voucherId", "ledgerId", "debitAmount", "creditAmount"],
        "business_metrics": ["debitAmount", "creditAmount"],
        "common_filters": ["voucherId", "ledgerId"],
        "common_groupby": ["ledgerId"],
    },
    "tbl_LeaveApplication": {
        "display_name": "Leave Applications",
        "domain": "HR",
        "module": "Leave Management",
        "description": "Employee leave applications with leave type, duration, reason, and approval status. Tracks leave balance consumption and manager approvals.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "leave", "leaves", "leave application", "leave applications",
            "leave request", "leave record", "leave details",
            "sick leave", "casual leave", "earned leave",
            "leave balance", "leave history", "time off"
        ],
        "common_user_intents": [
            "Show pending leave applications",
            "Leaves for employee X",
            "Approved leaves this month",
            "Leave balance for employee Y",
            "Total leaves taken this year",
            "Leave applications by status"
        ],
        "important_columns": ["employeeId", "leaveTypeId", "fromDate", "toDate", "totalDays", "statusId"],
        "business_metrics": ["totalDays"],
        "common_filters": ["employeeId", "leaveTypeId", "statusId"],
        "common_groupby": ["leaveTypeId", "statusId"],
    },
    "tbl_LeaveType": {
        "display_name": "Leave Types",
        "domain": "HR",
        "module": "Leave Management",
        "description": "Leave type master defining categories (Casual Leave, Sick Leave, Earned Leave, Maternity Leave, etc.) with annual quota and carry-forward rules.",
        "search_weight": 3, "priority": "Low",
        "search_keywords": [
            "leave type", "leave types", "leave category",
            "casual leave", "sick leave", "earned leave",
            "leave master", "leave name", "leave code",
            "paid leave", "unpaid leave", "maternity leave"
        ],
        "common_user_intents": [
            "List all leave types",
            "What leave types are available",
            "Leave types with quota",
            "Leave type master data"
        ],
        "important_columns": ["leaveCode", "leaveName", "maxDays"],
        "business_metrics": ["maxDays"],
        "common_filters": ["isActive"],
        "common_groupby": ["leaveCode"],
    },
    "tbl_LoadingDetail": {
        "display_name": "Loading Details",
        "domain": "Logistics",
        "module": "Warehouse Operations",
        "description": "Goods loading records for dispatch operations. Tracks what products, quantities, and packages are loaded onto vehicles for delivery.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "loading", "loading detail", "loading details",
            "loading record", "loading sheet", "loading list",
            "goods loading", "loading slip", "loading chit",
            "dispatch loading", "vehicle loading"
        ],
        "common_user_intents": [
            "Show loading details today",
            "Loading record for trip X",
            "What was loaded on vehicle Y",
            "Loading sheet for dispatch",
            "Products loaded today"
        ],
        "important_columns": ["tripId", "productId", "quantity", "loadingWeight", "unloadingWeight", "netWeight"],
        "business_metrics": ["quantity"],
        "common_filters": ["tripId", "productId"],
        "common_groupby": ["tripId", "productId"],
    },
    "tbl_OrgAddress": {
        "display_name": "Organization Addresses",
        "domain": "Organization",
        "module": "Organization Master",
        "description": "Physical addresses for organizations (offices, warehouses, godowns). Multiple addresses per organization for billing, shipping, and registered office.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "address", "addresses", "org address", "organization address",
            "billing address", "shipping address", "registered address",
            "office address", "warehouse address", "location",
            "office location", "godown address"
        ],
        "common_user_intents": [
            "Show addresses for organization X",
            "Billing address of dealer Y",
            "Warehouse locations",
            "All addresses for company Z",
            "Shipping addresses"
        ],
        "important_columns": ["organizationId", "addressType", "addressLine1", "cityId", "pinCode"],
        "business_metrics": [],
        "common_filters": ["organizationId", "addressType"],
        "common_groupby": ["addressType"],
    },
    "tbl_Organization": {
        "display_name": "Organizations",
        "domain": "Organization",
        "module": "Organization Master",
        "description": "Central master for all business partners including dealers, distributors, vendors, CNFs, and transporters. Stores firm name, GST/PAN details, contact info, credit limits, opening balances, and payment terms. Referenced across sales, purchase, and finance modules.",
        "search_weight": 9, "priority": "High",
        "search_keywords": [
            "organization", "organizations", "company", "companies",
            "dealer", "dealers", "distributor", "distributors",
            "vendor", "vendors", "supplier", "suppliers",
            "firm", "firms", "partner", "partners",
            "customer", "customers", "client", "clients",
            "buyer", "buyers", "party", "parties", "registered parties",
            "business partner", "business partners", "trader",
            "cnf", "transporter", "consignee", "consignees", "consignee list",
            "firm name", "company name", "org name",
            "dealer name", "vendor name", "customer name",
            "gst number", "pan number", "gstin",
            "credit limit", "opening balance",
            "contact person", "mobile number", "email",
            "org code", "organization code", "party code",
            "all parties", "party list", "organization list"
        ],
        "common_user_intents": [
            "Show dealer details",
            "List all vendors",
            "Organization with GST number X",
            "Companies with credit limit above Y",
            "Dealer contact details",
            "Get me total customers",
            "How many customers do we have",
            "List all customers",
            "Count customers by city",
            "Customers with credit limit above X",
            "Show all organizations",
            "Active dealers list",
            "Vendor master data",
            "Customer master data",
            "Partners with outstanding balance"
        ],
        "important_columns": ["orgCode", "firmName", "tradingName", "gstNo", "panNo", "creditLimit", "paymentTermId", "orgTypeId", "cityId"],
        "business_metrics": ["creditLimit", "openingBalance"],
        "common_filters": ["orgTypeId", "isActive", "cityId", "paymentTermId"],
        "common_groupby": ["orgTypeId", "cityId"],
    },
    "tbl_OrgBankDetail": {
        "display_name": "Organization Bank Details",
        "domain": "Organization",
        "module": "Organization Master",
        "description": "Bank account details for organizations including account number, IFSC, bank name, and branch. Used for payment processing and NEFT/RTGS transfers.",
        "search_weight": 4, "priority": "Medium",
        "search_keywords": [
            "bank detail", "bank details", "bank account", "bank accounts",
            "account number", "ifsc", "bank name", "branch name",
            "org bank", "organization bank", "payment bank",
            "neft", "rtgs", "bank information"
        ],
        "common_user_intents": [
            "Show bank details for organization X",
            "Bank account of dealer Y",
            "List bank accounts",
            "IFSC code for company Z",
            "Payment bank details"
        ],
        "important_columns": ["organizationId", "ifscCode", "bankName", "branchName"],
        "business_metrics": [],
        "common_filters": ["organizationId"],
        "common_groupby": [],
    },
    "tbl_OrgContact": {
        "display_name": "Organization Contacts",
        "domain": "Organization",
        "module": "Organization Master",
        "description": "Contact person details for organizations. Stores names, designations, phone numbers, emails, and WhatsApp for primary and secondary contacts.",
        "search_weight": 4, "priority": "Medium",
        "search_keywords": [
            "contact", "contacts", "org contact", "contact person",
            "contact details", "contact information", "phone number",
            "mobile number", "email", "whatsapp",
            "contact name", "person name", "key person"
        ],
        "common_user_intents": [
            "Show contacts for organization X",
            "Contact person at dealer Y",
            "Phone number of company Z",
            "Email contacts for vendors",
            "All contact details"
        ],
        "important_columns": ["organizationId", "contactName", "designation", "mobileNo", "email"],
        "business_metrics": [],
        "common_filters": ["organizationId"],
        "common_groupby": [],
    },
    "tbl_OrgRegistration": {
        "display_name": "Organization Registrations",
        "domain": "Compliance",
        "module": "Tax Compliance",
        "description": "Tax registration details for organizations including GSTIN, PAN, TAN, state codes, and registration types. Critical for tax compliance and invoice generation.",
        "search_weight": 4, "priority": "Medium",
        "search_keywords": [
            "registration", "registrations", "org registration",
            "gstin", "pan", "tan", "tax registration",
            "gst registration", "gst number", "pan number",
            "state code", "registration type", "tax id"
        ],
        "common_user_intents": [
            "Show registrations for organization X",
            "GSTIN of dealer Y",
            "Tax registrations list",
            "PAN details for company Z",
            "Registration by state"
        ],
        "important_columns": ["organizationId", "regType", "regNumber"],
        "business_metrics": [],
        "common_filters": ["organizationId", "regType"],
        "common_groupby": ["regType"],
    },
    "tbl_PaymentMade": {
        "display_name": "Payments Made",
        "domain": "Finance",
        "module": "Accounts Payable",
        "description": "Vendor payment records tracking amount paid, payment mode (NEFT/RTGS/Cheque/Cash), reference number, and linked purchase invoices.",
        "search_weight": 7, "priority": "High",
        "search_keywords": [
            "payment made", "payments made", "vendor payment", "vendor payments",
            "purchase payment", "payment to supplier", "payment to vendor",
            "payment record", "payment details", "payment list",
            "payment date", "payment amount", "payment mode",
            "neft", "rtgs", "cheque", "cash payment",
            "outgoing payment", "disbursement",
            "accounts payable", "payable", "expenses", "expenditure",
            "outflow", "cash out", "money paid", "total expenses",
            "dashboard", "expense dashboard", "payable dashboard",
            "pnl", "profit and loss", "p&l", "profit loss"
        ],
        "common_user_intents": [
            "Show payments made this month",
            "Payment to vendor X",
            "Total payments this quarter",
            "Payments by date range",
            "Pending payments",
            "Payment details for invoice Y"
        ],
        "important_columns": ["paymentNo", "paymentDate", "amount", "paymentMode", "referenceNo"],
        "business_metrics": ["amount"],
        "common_filters": ["vendorId", "paymentDate", "paymentMode"],
        "common_groupby": ["vendorId", "paymentMode", "paymentDate"],
    },
    "tbl_PaymentReceived": {
        "display_name": "Payments Received",
        "domain": "Finance",
        "module": "Accounts Receivable",
        "description": "Customer payment records tracking amount received, payment mode, reference number, and linked sale invoices. Core accounts receivable transaction.",
        "search_weight": 7, "priority": "High",
        "search_keywords": [
            "payment received", "payments received", "customer payment",
            "customer payments", "receipt", "receipts", "money received",
            "payment collection", "collection", "collections",
            "payment from customer", "dealer payment",
            "payment date", "payment amount", "payment mode",
            "incoming payment", "cash received",
            "accounts receivable", "receivable", "cash in", "money in",
            "dashboard", "finance dashboard", "collection dashboard",
            "pnl", "profit and loss", "p&l", "profit loss"
        ],
        "common_user_intents": [
            "Show payments received this month",
            "Payment from customer X",
            "Total collections this quarter",
            "Payments by date range",
            "Outstanding payments",
            "Payment details for invoice Y"
        ],
        "important_columns": ["paymentNo", "paymentDate", "organizationId", "amount", "paymentMode", "referenceNo"],
        "business_metrics": ["amount"],
        "common_filters": ["organizationId", "paymentDate", "paymentMode"],
        "common_groupby": ["paymentMode", "paymentDate"],
    },
    "tbl_PayrollDetail": {
        "display_name": "Payroll Details",
        "domain": "HR",
        "module": "Payroll Management",
        "description": "Line-level payroll records for each employee showing earnings (basic, HDA, DA, TA) and deductions (PF, ESI, TDS) within a payroll header.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "payroll detail", "payroll details", "salary detail",
            "salary details", "earnings", "deductions",
            "pf", "esi", "tds", "basic salary",
            "da", "hra", "ta", "pay slip", "payslip"
        ],
        "common_user_intents": [
            "Show salary details for employee X",
            "Payroll breakdown for month Y",
            "Earnings and deductions",
            "Salary slip for employee Z",
            "PF deduction details"
        ],
        "important_columns": ["payrollId", "componentName", "componentType", "amount"],
        "business_metrics": ["amount"],
        "common_filters": ["payrollId"],
        "common_groupby": ["componentName"],
    },
    "tbl_PayrollHeader": {
        "display_name": "Payroll Headers",
        "domain": "HR",
        "module": "Payroll Management",
        "description": "Monthly payroll batch headers summarizing total employees, total gross, total deductions, and net pay for a pay period. Contains payroll status and approval.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "payroll", "payroll header", "payroll batch",
            "salary", "salary batch", "monthly salary",
            "pay period", "pay month", "salary month",
            "gross salary", "net salary", "payroll summary",
            "payroll status", "salary processing"
        ],
        "common_user_intents": [
            "Show payroll this month",
            "Total salary expense",
            "Payroll batch status",
            "Processed payrolls",
            "Payroll summary for month X",
            "Total deductions this month"
        ],
        "important_columns": ["payMonth", "payYear", "grossPay", "totalDeductions", "netPay", "statusId"],
        "business_metrics": ["grossPay", "totalDeductions", "netPay"],
        "common_filters": ["payMonth", "payYear", "statusId"],
        "common_groupby": ["payMonth", "payYear"],
    },
    "tbl_PhysicalInventory": {
        "display_name": "Physical Inventory",
        "domain": "Inventory",
        "module": "Inventory Management",
        "description": "Physical stock count records comparing system stock with actual physical count. Used for annual/periodic inventory audits and stock reconciliation.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "physical inventory", "stock count", "physical count",
            "stock audit", "inventory audit", "stock verification",
            "physical stock", "stock take", "inventory count",
            "stock reconciliation", "variance report"
        ],
        "common_user_intents": [
            "Show physical inventory count",
            "Stock variance for product X",
            "Physical count results",
            "Inventory audit this month",
            "Stock discrepancy report"
        ],
        "important_columns": ["productId", "systemQty", "physicalQty", "warehouseId", "countDate"],
        "business_metrics": ["systemQty", "physicalQty"],
        "common_filters": ["productId", "warehouseId", "countDate"],
        "common_groupby": ["warehouseId", "countDate"],
    },
    "tbl_ProductCategory": {
        "display_name": "Product Categories",
        "domain": "Product",
        "module": "Product Master",
        "description": "Product category master for classifying products into groups (e.g., Raw Material, Finished Goods, Consumables). Top level of product hierarchy.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "product category", "product categories", "category",
            "categories", "product group", "item category",
            "item group", "product classification", "category master",
            "product type", "goods type", "edible", "edible oil",
        ],
        "common_user_intents": [
            "List all product categories",
            "Show category list",
            "Products in category X",
            "Category master data",
            "How many categories"
        ],
        "important_columns": ["categoryName", "categoryCode"],
        "business_metrics": [],
        "common_filters": ["isActive"],
        "common_groupby": [],
    },
    "tbl_ProductClass": {
        "display_name": "Product Classes",
        "domain": "Product",
        "module": "Product Master",
        "description": "Product class subclassification within categories. Provides finer grouping for product analysis and reporting.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "product class", "product classes", "class",
            "classes", "product subcategory", "item class",
            "product subclassification", "product type",
            "class master", "classification"
        ],
        "common_user_intents": [
            "List all product classes",
            "Show class list",
            "Products in class X",
            "Class master data",
            "Classes under category Y"
        ],
        "important_columns": ["className", "categoryId"],
        "business_metrics": [],
        "common_filters": ["isActive", "categoryId"],
        "common_groupby": ["categoryId"],
    },
    "tbl_ProductGrade": {
        "display_name": "Product Grades",
        "domain": "Product",
        "module": "Product Master",
        "description": "Product grade master for quality-based classification (Grade A, B, C, Premium). Used in pricing and quality management.",
        "search_weight": 4, "priority": "Medium",
        "search_keywords": [
            "product grade", "product grades", "grade", "grades",
            "grade master", "grade name", "grade code",
            "quality grade", "product quality", "grade list"
        ],
        "common_user_intents": [
            "List all product grades",
            "Show grade list",
            "Products with grade X",
            "Grade master data",
            "What grades are available"
        ],
        "important_columns": ["gradeName"],
        "business_metrics": [],
        "common_filters": ["isActive"],
        "common_groupby": [],
    },
    "tbl_ProductMaster": {
        "display_name": "Product Master",
        "domain": "Product",
        "module": "Product Master",
        "description": "Central product catalog storing product names, codes, HSN codes, categories, classes, brands, units of measure, GST applicability, minimum stock levels, and reorder quantities. Core entity referenced by inventory, pricing, sales, and purchase modules.",
        "search_weight": 9, "priority": "High",
        "search_keywords": [
            "product", "products", "item", "items", "material", "materials",
            "product master", "item master", "stock item", "goods",
            "product name", "product code", "hsn code", "hsn",
            "sku", "stock keeping unit", "product list", "product catalog",
            "brand", "brand list", "brands",
            "category", "class", "grade", "uom",
            "reorder level", "reorder qty", "min stock", "max stock",
            "gst applicable", "product details", "product information"
        ],
        "common_user_intents": [
            "Show product list",
            "What products do we have",
            "How many products are there",
            "Search product by name X",
            "Products in category Y",
            "Product master details",
            "Find product by HSN code",
            "Products below reorder level",
            "Product stock across warehouses",
            "List all brands",
            "Brand-wise product count"
        ],
        "important_columns": ["productName", "productCode", "categoryId", "classId", "baseUOMId", "gstRateId", "hsnCode", "minStock", "reorderLevel"],
        "business_metrics": ["minStock", "reorderLevel"],
        "common_filters": ["isActive", "categoryId", "classId"],
        "common_groupby": ["categoryId", "classId"],
    },
    "tbl_ProductPricing": {
        "display_name": "Product Pricing",
        "domain": "Pricing",
        "module": "Sales Pricing",
        "description": "Customer-specific product pricing overriding global sale rates. Allows setting custom prices per dealer/customer for specific products and grades.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "product pricing", "product price", "customer price",
            "dealer price", "special price", "custom price",
            "product pricing master", "price override", "customer pricing",
            "pricing by customer", "customer rate"
        ],
        "common_user_intents": [
            "Show pricing for product X",
            "Price list for customer Y",
            "Special prices for dealer Z",
            "Product pricing details",
            "Customer-specific rates"
        ],
        "important_columns": ["productId", "gradeId", "unitPrice"],
        "business_metrics": ["unitPrice"],
        "common_filters": ["productId", "gradeId"],
        "common_groupby": ["productId"],
    },
    "tbl_PurchaseEnquiry": {
        "display_name": "Purchase Enquiries",
        "domain": "Purchase",
        "module": "Purchase Management",
        "description": "Purchase enquiry/quotation request records sent to vendors for price quotes. Tracks enquiry date, required items, quantities, and response status.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "purchase enquiry", "purchase enquiries", "enquiry", "enquiries",
            "quotation request", "rfq", "request for quotation",
            "vendor enquiry", "supplier enquiry", "price enquiry",
            "purchase query", "quotation", "quote request",
            "indent", "purchase indent"
        ],
        "common_user_intents": [
            "Show purchase enquiries",
            "Open enquiries this month",
            "Enquiries to vendor X",
            "Pending quotations",
            "Enquiry details for product Y",
            "Quotation response status"
        ],
        "important_columns": ["enquiryNo", "enquiryDate", "vendorId", "expectedRate"],
        "business_metrics": ["expectedRate"],
        "common_filters": ["vendorId", "enquiryDate"],
        "common_groupby": ["vendorId", "enquiryDate"],
    },
    "tbl_PurchaseInvoice": {
        "display_name": "Purchase Invoices",
        "domain": "Purchase",
        "module": "Purchase Management",
        "description": "Purchase invoice/bill records from vendors tracking invoice number, date, amounts, tax, and linked purchase orders. Core accounts payable document.",
        "search_weight": 8, "priority": "High",
        "search_keywords": [
            "purchase invoice", "purchase invoices", "purchase bill",
            "vendor invoice", "vendor bill", "supplier invoice",
            "purchase entry", "purchase voucher", "purchase",
            "bill", "bills", "inward invoice", "purchase document",
            "invoice number", "invoice date", "invoice amount",
            "purchase total", "purchase gst", "purchase tax",
            "grn", "goods receipt", "purchase register"
        ],
        "common_user_intents": [
            "Show purchase invoices this month",
            "Bills from vendor X",
            "Total purchases this year",
            "Purchase invoice details",
            "Pending purchase bills",
            "Invoice for PO number Y"
        ],
        "important_columns": ["piNo", "piDate", "vendorId", "totalAmount", "purchaseOrderId"],
        "business_metrics": ["totalAmount"],
        "common_filters": ["vendorId", "piDate", "purchaseOrderId"],
        "common_groupby": ["vendorId", "piDate"],
    },
    "tbl_PurchaseOrder": {
        "display_name": "Purchase Orders",
        "domain": "Purchase",
        "module": "Purchase Management",
        "description": "Purchase order records for procurement from vendors. Contains PO number, date, items, quantities, rates, delivery dates, and approval status.",
        "search_weight": 8, "priority": "High",
        "search_keywords": [
            "purchase order", "purchase orders", "po", "pos",
            "purchase order list", "po list", "open po",
            "procurement order", "buy order", "supply order",
            "purchase contract", "order to vendor", "po number",
            "po date", "po amount", "po status",
            "pending po", "po approval", "po details"
        ],
        "common_user_intents": [
            "Show all purchase orders",
            "Open purchase orders",
            "POs for vendor X",
            "Purchase orders this month",
            "PO details for number Y",
            "Pending approvals for purchase orders"
        ],
        "important_columns": ["poNo", "poDate", "vendorId", "totalAmount", "statusId"],
        "business_metrics": ["totalAmount"],
        "common_filters": ["vendorId", "poDate", "statusId"],
        "common_groupby": ["vendorId", "poDate", "statusId"],
    },
    "tbl_PurchaseSchedule": {
        "display_name": "Purchase Schedules",
        "domain": "Purchase",
        "module": "Supply Chain",
        "description": "Purchase delivery schedules linked to purchase orders specifying scheduled delivery dates, quantities, and actual receipt tracking.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "purchase schedule", "purchase schedules", "delivery schedule",
            "supply schedule", "delivery plan", "receipt schedule",
            "purchase delivery", "schedule line", "supply plan",
            "delivery timeline"
        ],
        "common_user_intents": [
            "Show delivery schedules for PO X",
            "Overdue deliveries",
            "Scheduled receipts this week",
            "Purchase schedule details",
            "Delivery schedule for product Y"
        ],
        "important_columns": ["productId", "scheduleDate", "quantity"],
        "business_metrics": ["quantity"],
        "common_filters": ["productId", "scheduleDate"],
        "common_groupby": ["scheduleDate"],
    },
    "tbl_QualityChecklist": {
        "display_name": "Quality Checklists",
        "domain": "Quality",
        "module": "Quality Management",
        "description": "Quality inspection checklist templates defining parameters to check for each product or product category.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "quality checklist", "quality checklists", "checklist",
            "checklists", "inspection checklist", "quality template",
            "qc checklist", "quality check list", "inspection template"
        ],
        "common_user_intents": [
            "Show quality checklists",
            "Checklist for product X",
            "Inspection checklist details",
            "Quality parameters for product Y",
            "All checklists"
        ],
        "important_columns": ["checklistNo", "productId"],
        "business_metrics": [],
        "common_filters": ["productId"],
        "common_groupby": ["productId"],
    },
    "tbl_QualityParameter": {
        "display_name": "Quality Parameters",
        "domain": "Quality",
        "module": "Quality Management",
        "description": "Individual quality parameters/tests within a checklist. Defines acceptable ranges, units, and test methods for each quality metric.",
        "search_weight": 4, "priority": "Medium",
        "search_keywords": [
            "quality parameter", "quality parameters", "parameter",
            "parameters", "quality test", "test parameter",
            "qc parameter", "specification", "quality spec",
            "acceptance criteria"
        ],
        "common_user_intents": [
            "Show quality parameters for checklist X",
            "Parameters for product Y",
            "Quality specs for grade Z",
            "Parameter details",
            "Test parameters"
        ],
        "important_columns": ["paramCode", "paramName", "minValue", "maxValue"],
        "business_metrics": ["minValue", "maxValue"],
        "common_filters": ["productId"],
        "common_groupby": [],
    },
    "tbl_QualityTestResult": {
        "display_name": "Quality Test Results",
        "domain": "Quality",
        "module": "Quality Management",
        "description": "Records of actual quality test results for products against defined parameters. Captures test dates, measured values, pass/fail status, and tested by.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "quality test result", "quality test results", "test result",
            "test results", "qc result", "quality result",
            "inspection result", "quality report", "test report",
            "pass fail", "quality outcome"
        ],
        "common_user_intents": [
            "Show test results for product X",
            "Quality test report this month",
            "Failed tests today",
            "Test results for checklist Y",
            "Product quality history"
        ],
        "important_columns": ["checklistId", "parameterId", "testValue", "result"],
        "business_metrics": ["testValue"],
        "common_filters": ["checklistId", "parameterId", "result"],
        "common_groupby": ["checklistId", "parameterId", "result"],
    },
    "tbl_RateApproval": {
        "display_name": "Rate Approvals",
        "domain": "Pricing",
        "module": "Purchase Pricing",
        "description": "Rate approval records for vendor pricing negotiations. Tracks requested rates, approved rates, validity periods, and approval workflow.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "rate approval", "rate approvals", "price approval",
            "rate approval request", "price approval request",
            "rate negotiation", "rate confirmation", "approved rate",
            "vendor rate approval", "pricing approval"
        ],
        "common_user_intents": [
            "Show rate approvals",
            "Pending rate approvals",
            "Approved rates for product X",
            "Rate approval history",
            "Rate approvals this month"
        ],
        "important_columns": ["rateType", "requestedRate", "approvedRate", "approvalStatus"],
        "business_metrics": ["requestedRate", "approvedRate"],
        "common_filters": ["rateType", "approvalStatus"],
        "common_groupby": [],
    },
    "tbl_RateBand": {
        "display_name": "Rate Bands",
        "domain": "Pricing",
        "module": "Purchase Pricing",
        "description": "Rate band/price slabs for products based on order quantity. Defines tiered pricing (e.g., higher discount for larger quantities).",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "rate band", "rate bands", "price band", "price slabs",
            "tier pricing", "volume discount", "quantity bracket",
            "slab rate", "tiered pricing", "discount slab"
        ],
        "common_user_intents": [
            "Show rate bands for product X",
            "Price slabs for quantity Y",
            "Tiered pricing details",
            "Rate band list",
            "Volume discount brackets"
        ],
        "important_columns": ["globalPurchaseRateId", "bandFrom", "bandTo", "bandRate"],
        "business_metrics": ["bandRate"],
        "common_filters": ["globalPurchaseRateId", "isActive"],
        "common_groupby": [],
    },
    "tbl_RouteMaster": {
        "display_name": "Route Master",
        "domain": "Logistics",
        "module": "Logistics Management",
        "description": "Route master defining source-destination city pairs for transportation. Used in trip planning and freight cost calculation.",
        "search_weight": 4, "priority": "Medium",
        "search_keywords": [
            "route", "routes", "route master", "route list",
            "source destination", "city route", "transport route",
            "delivery route", "trip route", "route details",
            "route name", "route code"
        ],
        "common_user_intents": [
            "Show all routes",
            "Routes between city X and Y",
            "Route master data",
            "Available transport routes",
            "Route details"
        ],
        "important_columns": ["routeCode", "routeName", "sourceCityId", "destCityId", "distanceKm"],
        "business_metrics": ["distanceKm"],
        "common_filters": ["sourceCityId", "destCityId"],
        "common_groupby": ["sourceCityId", "destCityId"],
    },
    "tbl_SaleInvoiceDetail": {
        "display_name": "Sale Invoice Details",
        "domain": "Sales",
        "module": "Sales Management",
        "description": "Line-level details of sale invoices with product, quantity, rate, discount, tax, and amount for each invoice line item.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "sale invoice detail", "invoice detail", "invoice line",
            "invoice item", "sale invoice line", "billing detail",
            "invoice row", "invoice product", "invoice entry",
            "invoice breakdown"
        ],
        "common_user_intents": [
            "Show invoice line items for invoice X",
            "Products sold in invoice Y",
            "Invoice detail breakdown",
            "Invoice item details",
            "Quantity and rate per product"
        ],
        "important_columns": ["invoiceId", "productId", "quantity", "unitPrice", "discountAmt", "taxAmount", "netAmount"],
        "business_metrics": ["quantity", "unitPrice", "discountAmt", "taxAmount", "netAmount"],
        "common_filters": ["invoiceId", "productId"],
        "common_groupby": ["invoiceId", "productId"],
    },
    "tbl_SaleInvoiceHeader": {
        "display_name": "Sale Invoice Headers",
        "domain": "Sales",
        "module": "Sales Management",
        "description": "Sales invoice header with invoice number, date, dealer/customer, grand total, GST details, payment terms, and status. Central document for revenue recognition and accounts receivable.",
        "search_weight": 9, "priority": "High",
        "search_keywords": [
            "sale invoice", "sale invoices", "sales invoice", "sales invoices",
            "invoice", "invoices", "billing", "bill",
            "sales bill", "sale bill", "customer invoice",
            "dealer invoice", "sales document", "sales transaction",
            "invoice number", "invoice date", "invoice amount",
            "grand total", "invoice total",
            "gst invoice", "tax invoice", "invoice status",
            "pending invoice", "paid invoice", "cancelled invoice",
            "outstanding invoice", "overdue invoice",
            "accounts receivable", "receivable", "debtor",
            "credit sale", "sales register",
            "revenue", "sales revenue", "turnover", "sales total",
            "daily sales", "monthly sales", "yearly sales",
            "dashboard", "sales dashboard",
            "pnl", "profit and loss", "p&l", "profit loss"
        ],
        "common_user_intents": [
            "Show all invoices",
            "Pending invoices this month",
            "Invoice details for invoice number X",
            "Total sales this month",
            "Sales by customer Y",
            "Outstanding invoices",
            "Invoices by date range",
            "Monthly sales report",
            "Sales dashboard"
        ],
        "important_columns": ["invoiceNo", "invoiceDate", "dealerOrgId", "grandTotal"],
        "business_metrics": ["grandTotal"],
        "common_filters": ["dealerOrgId", "invoiceDate"],
        "common_groupby": ["dealerOrgId", "invoiceDate", "invoiceType"],
    },
    "tbl_SaleOrder": {
        "display_name": "Sale Orders",
        "domain": "Sales",
        "module": "Sales Management",
        "description": "Sales order records capturing customer requests for products, including order number, date, delivery date, pricing, and approval status.",
        "search_weight": 7, "priority": "High",
        "search_keywords": [
            "sale order", "sale orders", "sales order", "sales orders",
            "so", "customer order", "customer orders",
            "order", "orders", "order booking", "sales booking",
            "order number", "order date", "order amount",
            "order status", "pending order", "confirmed order",
            "customer demand", "buyer order",
            "order details", "order list"
        ],
        "common_user_intents": [
            "Show all sale orders",
            "Pending orders this month",
            "Orders from customer X",
            "Order details for number Y",
            "Total orders this year",
            "Order status summary"
        ],
        "important_columns": ["orderNo", "orderDate", "organizationId", "totalAmount", "statusId", "deliveryDate"],
        "business_metrics": ["totalAmount"],
        "common_filters": ["organizationId", "orderDate", "statusId"],
        "common_groupby": ["organizationId", "orderDate", "statusId"],
    },
    "tbl_SaleOrderDetail": {
        "display_name": "Sale Order Details",
        "domain": "Sales",
        "module": "Sales Management",
        "description": "Line-level details of sale orders specifying products, quantities, rates, discounts, and delivery schedules requested by the customer.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "sale order detail", "order detail", "order line",
            "order item", "sale order line", "order product",
            "order quantity", "order rate",
            "so detail", "sales order detail",
            "order breakdown"
        ],
        "common_user_intents": [
            "Show order line items for SO X",
            "Products ordered by customer Y",
            "Order detail breakdown",
            "Quantity and rate per product",
            "Order item details"
        ],
        "important_columns": ["saleOrderId", "productId", "quantity", "unitPrice", "totalAmount"],
        "business_metrics": ["quantity", "unitPrice", "totalAmount"],
        "common_filters": ["saleOrderId", "productId"],
        "common_groupby": ["saleOrderId", "productId"],
    },
    "tbl_SaleReturn": {
        "display_name": "Sale Returns",
        "domain": "Sales",
        "module": "Returns Management",
        "description": "Sales return records for goods returned by customers. Tracks return reason, quantities, amounts, and linked sale invoices for credit processing.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "sale return", "sale returns", "sales return", "sales returns",
            "return", "returns", "customer return",
            "returned goods", "return order", "return request",
            "return reason", "return quantity", "return amount",
            "reverse logistics", "returned product",
            "return details"
        ],
        "common_user_intents": [
            "Show sale returns this month",
            "Returns from customer X",
            "Return reasons summary",
            "Total returns value",
            "Return details for invoice Y"
        ],
        "important_columns": ["returnNo", "returnDate", "organizationId", "totalAmount", "invoiceId"],
        "business_metrics": ["totalAmount"],
        "common_filters": ["organizationId", "returnDate", "invoiceId"],
        "common_groupby": ["returnDate"],
    },
    "tbl_StockLedger": {
        "display_name": "Stock Ledger",
        "domain": "Inventory",
        "module": "Inventory Management",
        "description": "Inventory stock ledger tracking product quantities across warehouses. Records opening, inward, outward, and closing stock for each product/warehouse combination.",
        "search_weight": 8, "priority": "High",
        "search_keywords": [
            "stock ledger", "stock", "inventory", "stock balance",
            "stock quantity", "stock level", "inventory level",
            "warehouse stock", "product stock", "available stock",
            "stock in hand", "closing stock", "opening stock",
            "stock movement", "stock record", "stock detail",
            "inventory ledger", "material stock",
            "current stock", "stock by warehouse",
            "stock by product", "stock status"
        ],
        "common_user_intents": [
            "Show current stock for product X",
            "Stock balance across warehouses",
            "Products below minimum stock",
            "Stock ledger for product Y",
            "Inventory status",
            "Stock in warehouse Z",
            "Available quantity for product X",
            "Stock levels by product"
        ],
        "important_columns": ["productId", "warehouseId", "inQty", "outQty", "balanceQty"],
        "business_metrics": ["inQty", "outQty", "balanceQty"],
        "common_filters": ["productId", "warehouseId"],
        "common_groupby": ["productId", "warehouseId"],
    },
    "tbl_StockTransfer": {
        "display_name": "Stock Transfers",
        "domain": "Inventory",
        "module": "Inventory Management",
        "description": "Inter-warehouse stock transfer records tracking product movement between warehouses. Includes transfer date, quantity, source, destination, and status.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "stock transfer", "stock transfers", "warehouse transfer",
            "inter warehouse transfer", "stock movement", "transfer",
            "material transfer", "inventory transfer",
            "transfer order", "transfer quantity",
            "stock shift", "goods transfer"
        ],
        "common_user_intents": [
            "Show stock transfers this month",
            "Transfers from warehouse X to Y",
            "Pending transfers",
            "Stock transfer history",
            "Transfer details for product Z"
        ],
        "important_columns": ["productId", "fromWarehouseId", "toWarehouseId", "quantity", "transferDate"],
        "business_metrics": ["quantity"],
        "common_filters": ["productId", "fromWarehouseId", "toWarehouseId", "transferDate"],
        "common_groupby": ["fromWarehouseId", "toWarehouseId", "transferDate"],
    },
    "tbl_TDSDeduction": {
        "display_name": "TDS Deductions",
        "domain": "Compliance",
        "module": "Tax Compliance",
        "description": "TDS deduction records tracking tax withheld on payments to vendors. Includes TDS section, rate, amount, challan details, and filing status.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "tds", "tds deduction", "tds deductions", "tax deducted",
            "withholding tax", "tds certificate", "tds challan",
            "tds return", "tds payment", "tds rate",
            "tax withholding", "tds details",
            "tds on purchase", "tds on payment"
        ],
        "common_user_intents": [
            "Show TDS deductions for vendor X",
            "TDS deducted this month",
            "Pending TDS payments",
            "TDS deduction details",
            "TDS certificates issued"
        ],
        "important_columns": ["organizationId", "tdsSection", "tdsAmount", "challanNo", "tdsDate"],
        "business_metrics": ["tdsAmount"],
        "common_filters": ["organizationId", "tdsDate"],
        "common_groupby": ["tdsSection", "tdsDate"],
    },
    "tbl_TripSheet": {
        "display_name": "Trip Sheets",
        "domain": "Logistics",
        "module": "Logistics Management",
        "description": "Trip sheet records for goods transportation tracking trip number, date, vehicle, driver, route, loading/unloading details, expenses, and trip status.",
        "search_weight": 7, "priority": "Medium",
        "search_keywords": [
            "trip sheet", "trip sheets", "trip", "trips",
            "delivery trip", "transport trip", "goods trip",
            "trip number", "trip date", "trip details",
            "trip status", "trip report",
            "logistics trip", "transportation trip"
        ],
        "common_user_intents": [
            "Show trips today",
            "Trip details for trip number X",
            "Trips by driver Y",
            "Trip expenses this month",
            "Trip status report",
            "Completed trips today"
        ],
        "important_columns": ["tripNo", "tripDate", "vehicleId", "driverId", "routeId", "statusId"],
        "business_metrics": ["totalKm"],
        "common_filters": ["tripDate", "vehicleId", "driverId", "statusId"],
        "common_groupby": ["vehicleId", "driverId", "tripDate", "statusId"],
    },
    "tbl_UserMaster": {
        "display_name": "User Master",
        "domain": "System",
        "module": "System Administration",
        "description": "System user accounts for application login. Stores username, password hash, role, and active status for authentication and authorization.",
        "search_weight": 3, "priority": "Low",
        "search_keywords": [
            "user", "users", "user master", "login",
            "user account", "user name", "user role",
            "system user", "application user",
            "user access", "user authentication"
        ],
        "common_user_intents": [
            "Show active users",
            "System users list",
            "User roles and permissions",
            "User master data",
            "Login accounts"
        ],
        "important_columns": ["userName", "userRole", "fullName"],
        "business_metrics": [],
        "common_filters": ["isActive", "userRole"],
        "common_groupby": ["userRole"],
    },
    "tbl_VendorEvaluation": {
        "display_name": "Vendor Evaluation",
        "domain": "Purchase",
        "module": "Vendor Management",
        "description": "Vendor performance evaluation records with scores in various categories (quality, delivery, price, service) and overall rating.",
        "search_weight": 6, "priority": "Medium",
        "search_keywords": [
            "vendor evaluation", "vendor evaluation", "vendor rating",
            "supplier evaluation", "supplier rating", "vendor score",
            "vendor performance", "supplier performance",
            "vendor assessment", "vendor review",
            "evaluation score", "vendor quality score"
        ],
        "common_user_intents": [
            "Show vendor evaluation scores",
            "Top rated vendors",
            "Vendor performance report",
            "Evaluation details for vendor X",
            "Vendor scorecard"
        ],
        "important_columns": ["vendorId", "overallScore", "evaluationDate"],
        "business_metrics": ["overallScore"],
        "common_filters": ["vendorId", "evaluationDate"],
        "common_groupby": ["vendorId"],
    },
    "tbl_VehicleMaster": {
        "display_name": "Vehicle Master",
        "domain": "Logistics",
        "module": "Fleet Management",
        "description": "Vehicle master with registration details, type, capacity, insurance, fitness, and ownership. Used in trip planning and fleet management.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "vehicle", "vehicles", "vehicle master", "vehicle list",
            "truck", "lorry", "tempo", "container",
            "vehicle number", "vehicle type", "vehicle capacity",
            "registration number", "rc", "insurance",
            "fleet", "fleet management", "transport vehicle",
            "vehicle details"
        ],
        "common_user_intents": [
            "List all vehicles",
            "Vehicle details for number X",
            "Available vehicles today",
            "Vehicle master data",
            "Vehicles by type",
            "Fleet list"
        ],
        "important_columns": ["vehicleNo", "vehicleType", "capacity"],
        "business_metrics": ["capacity"],
        "common_filters": ["isActive", "vehicleType"],
        "common_groupby": ["vehicleType"],
    },
    "tbl_Warehouse": {
        "display_name": "Warehouses",
        "domain": "Inventory",
        "module": "Inventory Management",
        "description": "Warehouse/godown master storing location details, type, capacity, and contact. Physical storage locations for inventory management.",
        "search_weight": 5, "priority": "Medium",
        "search_keywords": [
            "warehouse", "warehouses", "godown", "godowns",
            "store", "stores", "storage location", "storage",
            "warehouse name", "warehouse code", "warehouse type",
            "warehouse location", "warehouse capacity",
            "inventory location", "stock location"
        ],
        "common_user_intents": [
            "List all warehouses",
            "Warehouse details for location X",
            "Storage locations",
            "Warehouse master data",
            "Warehouses in city Y",
            "Warehouse capacity"
        ],
        "important_columns": ["warehouseName", "warehouseCode", "cityId"],
        "business_metrics": [],
        "common_filters": ["isActive", "cityId"],
        "common_groupby": ["cityId"],
    },
}


COLUMN_META = {
}


ACTIVE_ALIASES = {
    "description": "Whether the record is currently active (soft delete flag)",
    "role": "status",
    "importance": "high",
    "aliases": ["active", "enabled", "is active", "active record", "enabled record"],
    "sample_values": ["Yes", "No"],
    "search_keywords": ["active", "enabled", "soft delete", "live"],
    "common_user_intents": ["Filter active records", "Show only active items", "What is active"],
    "aggregations_allowed": [],
}
