"""Comprehensive term dictionary for fuzzy correction, typo fixing, and query understanding.

Sections:
  TABLE_ALIASES     - Maps table name to all business alias phrases
  VALUE_CORRECTIONS - Maps common misspellings/alternates to canonical correct value
  ENUM_VALUES       - All known enumerated values per (table, column)
  BUSINESS_TERMS    - Business acronyms and domain terms beyond the base glossary
  SUCCESSFUL_QUERIES - Historically successful NL queries for reference
"""


TABLE_ALIASES = {
    "dim_OrgType": ["org type", "organization type", "party type", "partner type", "dealer type", "vendor type", "distributor type", "entity type", "org category", "organization category", "party category", "business partner type"],
    "dim_PaymentTerm": ["payment term", "payment terms", "pay terms", "credit terms", "due days", "net days", "payment due", "payment condition", "credit period", "payment mode", "terms of payment", "payment schedule", "invoice terms"],
    "dim_Status": ["status", "order status", "invoice status", "delivery status", "status code", "status name", "status master", "approval status", "payment status", "fulfillment status", "status category"],
    "dim_TaxRate": ["tax rate", "tax rates", "gst rate", "gst rates", "sgst", "cgst", "igst", "tax percentage", "tax slab", "tax master", "tax code", "tax name", "goods and services tax", "tax category"],
    "dim_UOM": ["uom", "unit", "units", "unit of measurement", "measurement unit", "quantity unit", "weight unit", "kilogram", "litre", "piece", "box", "metric ton", "uom master", "unit master"],
    "dmn_City": ["city", "cities", "town", "district", "location", "city master", "city list", "city name", "pin code", "postal code", "city code", "place", "area", "municipality", "metro", "locality", "pincode", "zip code", "zip"],
    "dmn_Country": ["country", "countries", "nation", "country master", "country list", "country code", "country name", "international", "domestic", "global", "worldwide", "iso country", "country lookup"],
    "dmn_State": ["state", "states", "state master", "state list", "state code", "state name", "gst state code", "region", "province", "territory", "division", "state lookup", "maharashtra", "gujarat", "rajasthan", "karnataka", "tamil nadu", "kerala", "andhra pradesh", "telangana", "uttar pradesh", "delhi", "haryana", "punjab", "madhya pradesh", "west bengal", "bihar", "odisha", "assam", "jharkhand", "chhattisgarh", "himachal", "uttarakhand", "goa"],
    "tbl_AccountGroup": ["account group", "account groups", "ledger group", "chart of accounts", "account category", "account head", "financial group", "gl group", "general ledger group", "account hierarchy", "parent account"],
    "tbl_AccountLedger": ["ledger", "ledgers", "account ledger", "account ledgers", "gl", "general ledger", "account head", "account name", "financial ledger", "account balance", "debit credit", "trial balance", "account code"],
    "tbl_Attendance": ["attendance", "employee attendance", "check in", "check out", "present", "absent", "half day", "work hours", "overtime", "daily attendance", "attendance record", "punch in", "punch out", "attendance report"],
    "tbl_AuditLog": ["audit log", "audit trail", "activity log", "change log", "user activity", "system log", "action log", "audit record", "modification history", "who changed"],
    "tbl_Booking": ["booking", "bookings", "sales booking", "customer booking", "order booking", "booking details", "booking record", "booking number", "booking date", "booking status", "reservation", "sales order", "demand"],
    "tbl_BookingDelivery": ["delivery", "deliveries", "booking delivery", "shipment", "dispatch", "delivery details", "delivery status", "delivery date", "delivery tracking", "goods delivery", "consignment", "delivery note"],
    "tbl_CreditDebitNote": ["credit note", "debit note", "credit notes", "debit notes", "cdn", "dbn", "credit debit note", "adjustment note", "return note", "allowance", "rebate", "discount note", "purchase return", "sales return", "credit debit"],
    "tbl_Department": ["department", "departments", "dept", "department master", "department name", "organizational unit", "team", "division", "section", "unit"],
    "tbl_Designation": ["designation", "designations", "job title", "job titles", "role", "position", "rank", "grade", "designation master", "title master", "job role"],
    "tbl_DriverMaster": ["driver", "drivers", "driver master", "driver list", "chauffeur", "transporter driver", "driver name", "license number", "driver details", "driver contact", "vehicle driver"],
    "tbl_Employee": ["employee", "employees", "staff", "staff member", "staff members", "worker", "workers", "personnel", "team member", "emp", "employee list", "employee master", "human resource", "hr", "manpower", "workforce", "employee name", "employee code", "headcount", "new joiners", "joining", "new employee", "recent joiners"],
    "tbl_ErrorLog": ["error log", "error logs", "exception", "exceptions", "error", "errors", "bug", "system error", "application error", "crash log", "error report"],
    "tbl_EwayBill": ["eway bill", "e-way bill", "eway bills", "e-way bills", "eway", "ewaybill", "eway bill number", "eway bill details", "goods movement", "transport document", "eway generated", "eway bill status"],
    "tbl_GSTReturn": ["gst return", "gst returns", "gstr", "gstr1", "gstr3b", "tax return", "gst filing", "return filing", "gst submission", "monthly return", "quarterly return", "gst compliance", "tax filing status"],
    "tbl_GlobalPurchaseRate": ["purchase rate", "purchase rates", "buying rate", "cost price", "purchase price", "vendor rate", "supplier rate", "buying price", "procurement rate", "purchase rate master", "global rate", "standard rate"],
    "tbl_GlobalSaleRate": ["sale rate", "sale rates", "selling rate", "selling price", "sale price", "customer rate", "dealer rate", "mrp", "list price", "price list", "global rate", "standard rate", "product rate", "pricing"],
    "tbl_InventoryAdjustment": ["inventory adjustment", "stock adjustment", "stock correction", "adjustment", "adjustments", "inventory correction", "stock variance", "damage write off", "expiry adjustment", "physical adjustment", "stock loss", "stock gain"],
    "tbl_JournalVoucher": ["journal voucher", "journal vouchers", "journal entry", "journal entries", "jv", "journal book", "accounting entry", "debit credit entry", "general journal", "journal record", "financial entry"],
    "tbl_JournalVoucherDetail": ["journal detail", "journal line", "journal voucher detail", "debit entry", "credit entry", "ledger entry", "journal line item", "accounting detail"],
    "tbl_LeaveApplication": ["leave", "leaves", "leave application", "leave applications", "leave request", "leave record", "leave details", "sick leave", "casual leave", "earned leave", "leave balance", "leave history", "time off"],
    "tbl_LeaveType": ["leave type", "leave types", "leave category", "casual leave", "sick leave", "earned leave", "leave master", "leave name", "leave code", "paid leave", "unpaid leave", "maternity leave"],
    "tbl_LoadingDetail": ["loading", "loading detail", "loading details", "loading record", "loading sheet", "loading list", "goods loading", "loading slip", "loading chit", "dispatch loading", "vehicle loading"],
    "tbl_OrgAddress": ["address", "addresses", "org address", "organization address", "billing address", "shipping address", "registered address", "office address", "warehouse address", "location", "office location", "godown address"],
    "tbl_OrgBankDetail": ["bank detail", "bank details", "bank account", "bank accounts", "account number", "ifsc", "bank name", "branch name", "org bank", "organization bank", "payment bank", "neft", "rtgs", "bank information"],
    "tbl_OrgContact": ["contact", "contacts", "org contact", "contact person", "contact details", "contact information", "phone number", "mobile number", "email", "whatsapp", "contact name", "person name", "key person"],
    "tbl_OrgRegistration": ["registration", "registrations", "org registration", "gstin", "pan", "tan", "tax registration", "gst registration", "gst number", "pan number", "state code", "registration type", "tax id"],
    "tbl_Organization": ["organization", "organizations", "company", "companies", "dealer", "dealers", "distributor", "distributors", "vendor", "vendors", "supplier", "suppliers", "firm", "firms", "partner", "partners", "customer", "customers", "client", "clients", "buyer", "buyers", "party", "parties", "business partner", "business partners", "trader", "cnf", "transporter", "consignee", "firm name", "company name", "org name", "dealer name", "vendor name", "customer name", "gst number", "pan number", "gstin", "credit limit", "opening balance", "org code", "organization code", "party code"],
    "tbl_PaymentMade": ["payment made", "payments made", "vendor payment", "vendor payments", "purchase payment", "payment to supplier", "payment to vendor", "payment record", "payment details", "payment date", "payment amount", "payment mode", "neft", "rtgs", "cheque", "cash payment", "outgoing payment", "disbursement", "accounts payable", "payable", "expenses", "expenditure", "outflow", "cash out", "money paid", "total expenses"],
    "tbl_PaymentReceived": ["payment received", "payments received", "customer payment", "customer payments", "receipt", "receipts", "money received", "payment collection", "collection", "collections", "payment from customer", "dealer payment", "incoming payment", "cash received", "accounts receivable", "receivable", "cash in", "money in"],
    "tbl_PayrollDetail": ["payroll detail", "payroll details", "salary detail", "salary details", "earnings", "deductions", "pf", "esi", "tds", "basic salary", "da", "hra", "ta", "pay slip", "payslip"],
    "tbl_PayrollHeader": ["payroll", "payroll header", "payroll batch", "salary", "salary batch", "monthly salary", "pay period", "pay month", "salary month", "gross salary", "net salary", "payroll summary", "payroll status", "salary processing"],
    "tbl_PhysicalInventory": ["physical inventory", "stock count", "physical count", "stock audit", "inventory audit", "stock verification", "physical stock", "stock take", "inventory count", "stock reconciliation", "variance report"],
    "tbl_ProductCategory": ["product category", "product categories", "category", "categories", "product group", "item category", "item group", "product classification", "category master", "product type", "goods type"],
    "tbl_ProductClass": ["product class", "product classes", "class", "classes", "product subcategory", "item class", "product subclassification", "product type", "class master", "classification"],
    "tbl_ProductGrade": ["product grade", "product grades", "grade", "grades", "grade master", "grade name", "grade code", "quality grade", "product quality", "grade list"],
    "tbl_ProductMaster": ["product", "products", "item", "items", "material", "materials", "product master", "item master", "stock item", "goods", "product name", "product code", "hsn code", "hsn", "sku", "stock keeping unit", "product list", "product catalog", "brand", "brand list", "brands", "category", "class", "grade", "uom", "reorder level", "reorder qty", "min stock", "max stock", "product details", "product information"],
    "tbl_ProductPricing": ["product pricing", "product price", "customer price", "dealer price", "special price", "custom price", "product pricing master", "price override", "customer pricing", "pricing by customer", "customer rate"],
    "tbl_PurchaseEnquiry": ["purchase enquiry", "purchase enquiries", "enquiry", "enquiries", "quotation request", "rfq", "request for quotation", "vendor enquiry", "supplier enquiry", "price enquiry", "purchase query", "quotation", "quote request", "indent", "purchase indent"],
    "tbl_PurchaseInvoice": ["purchase invoice", "purchase invoices", "purchase bill", "vendor invoice", "vendor bill", "supplier invoice", "purchase entry", "purchase voucher", "purchase", "bill", "bills", "inward invoice", "invoice number", "invoice date", "invoice amount", "purchase total", "purchase gst", "purchase tax", "grn", "goods receipt", "purchase register"],
    "tbl_PurchaseOrder": ["purchase order", "purchase orders", "po", "pos", "purchase order list", "po list", "open po", "procurement order", "buy order", "supply order", "purchase contract", "order to vendor", "po number", "po date", "po amount", "po status", "pending po", "po approval", "po details"],
    "tbl_PurchaseSchedule": ["purchase schedule", "purchase schedules", "delivery schedule", "supply schedule", "delivery plan", "receipt schedule", "purchase delivery", "schedule line", "supply plan", "delivery timeline"],
    "tbl_QualityChecklist": ["quality checklist", "quality checklists", "checklist", "checklists", "inspection checklist", "quality template", "qc checklist", "quality check list", "inspection template"],
    "tbl_QualityParameter": ["quality parameter", "quality parameters", "parameter", "parameters", "quality test", "test parameter", "qc parameter", "specification", "quality spec", "acceptance criteria"],
    "tbl_QualityTestResult": ["quality test result", "quality test results", "test result", "test results", "qc result", "quality result", "inspection result", "quality report", "test report", "pass fail", "quality outcome"],
    "tbl_RateApproval": ["rate approval", "rate approvals", "price approval", "rate approval request", "price approval request", "rate negotiation", "rate confirmation", "approved rate", "vendor rate approval", "pricing approval"],
    "tbl_RateBand": ["rate band", "rate bands", "price band", "price slabs", "tier pricing", "volume discount", "quantity bracket", "slab rate", "tiered pricing", "discount slab"],
    "tbl_RouteMaster": ["route", "routes", "route master", "route list", "source destination", "city route", "transport route", "delivery route", "trip route", "route details", "route name", "route code"],
    "tbl_SaleInvoiceDetail": ["sale invoice detail", "invoice detail", "invoice line", "invoice item", "sale invoice line", "billing detail", "invoice row", "invoice product", "invoice entry", "invoice breakdown"],
    "tbl_SaleInvoiceHeader": ["sale invoice", "sale invoices", "sales invoice", "sales invoices", "invoice", "invoices", "billing", "bill", "sales bill", "sale bill", "customer invoice", "dealer invoice", "sales document", "sales transaction", "invoice number", "invoice date", "invoice amount", "grand total", "invoice total", "gst invoice", "tax invoice", "invoice status", "pending invoice", "paid invoice", "cancelled invoice", "outstanding invoice", "overdue invoice", "accounts receivable", "receivable", "debtor", "credit sale", "sales register", "revenue", "sales revenue", "turnover", "sales total", "daily sales", "monthly sales", "yearly sales"],
    "tbl_SaleOrder": ["sale order", "sale orders", "sales order", "sales orders", "so", "customer order", "customer orders", "order", "orders", "order booking", "sales booking", "order number", "order date", "order amount", "order status", "pending order", "confirmed order", "customer demand", "buyer order", "order details"],
    "tbl_SaleOrderDetail": ["sale order detail", "order detail", "order line", "order item", "sale order line", "order product", "order quantity", "order rate", "so detail", "sales order detail", "order breakdown"],
    "tbl_SaleReturn": ["sale return", "sale returns", "sales return", "sales returns", "return", "returns", "customer return", "returned goods", "return order", "return request", "return reason", "return quantity", "return amount", "reverse logistics", "returned product", "return details"],
    "tbl_StockLedger": ["stock ledger", "stock", "inventory", "stock balance", "stock quantity", "stock level", "inventory level", "warehouse stock", "product stock", "available stock", "stock in hand", "closing stock", "opening stock", "stock movement", "stock record", "inventory ledger", "material stock", "current stock", "stock by warehouse", "stock by product"],
    "tbl_StockTransfer": ["stock transfer", "stock transfers", "warehouse transfer", "inter warehouse transfer", "stock movement", "transfer", "material transfer", "inventory transfer", "transfer order", "transfer quantity", "stock shift", "goods transfer"],
    "tbl_TDSDeduction": ["tds", "tds deduction", "tds deductions", "tax deducted", "withholding tax", "tds certificate", "tds challan", "tds return", "tds payment", "tds rate", "tax withholding", "tds details", "tds on purchase", "tds on payment"],
    "tbl_TripSheet": ["trip sheet", "trip sheets", "trip", "trips", "delivery trip", "transport trip", "goods trip", "trip number", "trip date", "trip details", "trip status", "trip report", "logistics trip", "transportation trip"],
    "tbl_UserMaster": ["user", "users", "user master", "login", "user account", "user name", "user role", "system user", "application user", "user access", "user authentication"],
    "tbl_VehicleMaster": ["vehicle", "vehicles", "vehicle master", "vehicle list", "truck", "lorry", "tempo", "container", "vehicle number", "vehicle type", "vehicle capacity", "registration number", "rc", "insurance", "fleet", "fleet management", "transport vehicle", "vehicle details"],
    "tbl_VendorEvaluation": ["vendor evaluation", "vendor rating", "supplier evaluation", "supplier rating", "vendor score", "vendor performance", "supplier performance", "vendor assessment", "vendor review", "evaluation score", "vendor quality score"],
    "tbl_Warehouse": ["warehouse", "warehouses", "godown", "godowns", "store", "stores", "storage location", "storage", "warehouse name", "warehouse code", "warehouse type", "warehouse location", "warehouse capacity", "inventory location", "stock location"],
}


VALUE_CORRECTIONS = {
    "12%": "GST 12%",
    "18%": "GST 18%",
    "28%": "GST 28%",
    "5%": "GST 5%",
    "a grade": "Grade A",
    "a negative": "A-",
    "a positive": "A+",
    "a+": "A+",
    "a-": "A-",
    "ab negative": "AB-",
    "ab positive": "AB+",
    "ab+": "AB+",
    "ab-": "AB-",
    "absent": "Absent",
    "abst": "Absent",
    "active": "Active",
    "actv": "Active",
    "addr": "Address",
    "address": "Address",
    "adr": "Address",
    "adv": "Advance",
    "advance": "Advance",
    "advance payment": "Advance",
    "agra": "Agra",
    "ahmedabad": "Ahmedabad",
    "ajmer": "Ajmer",
    "allahabad": "Prayagraj",
    "alwar": "Alwar",
    "amdavad": "Ahmedabad",
    "amount": "Amount",
    "amritsar": "Amritsar",
    "amt": "Amount",
    "anand": "Anand",
    "anantapur": "Anantapur",
    "andhra": "Andhra Pradesh",
    "andhra pradesh": "Andhra Pradesh",
    "approval": "Approval",
    "approved": "Approved",
    "apprvd": "Approved",
    "apprvl": "Approval",
    "aprovd": "Approved",
    "arunachal pradesh": "Arunachal Pradesh",
    "asansol": "Asansol",
    "assam": "Assam",
    "asset": "Asset",
    "assets": "Asset",
    "attend": "Attendance",
    "attendance": "Attendance",
    "attendence": "Attendance",
    "aurangabad": "Aurangabad",
    "b grade": "Grade B",
    "b negative": "B-",
    "b positive": "B+",
    "b+": "B+",
    "b-": "B-",
    "bag": "Bag",
    "ballari": "Bellary",
    "banaras": "Varanasi",
    "bangalore": "Bangalore",
    "banglore": "Bangalore",
    "bank transfer": "Bank Transfer",
    "banktransfer": "Bank Transfer",
    "baroda": "Vadodara",
    "bathinda": "Bathinda",
    "belagavi": "Belgaum",
    "belgaum": "Belgaum",
    "bellary": "Bellary",
    "bengalooru": "Bangalore",
    "bengaluru": "Bangalore",
    "bereavement leave": "Bereavement Leave",
    "bharatpur": "Bharatpur",
    "bhatinda": "Bathinda",
    "bhavnagar": "Bhavnagar",
    "bhiwani": "Bhiwani",
    "bhopal": "Bhopal",
    "bhubaneshwar": "Bhubaneswar",
    "bhubaneswar": "Bhubaneswar",
    "bhuvneshwar": "Bhubaneswar",
    "bihar": "Bihar",
    "bikaner": "Bikaner",
    "bill": "Billing",
    "billing": "Billing",
    "bombay": "Mumbai",
    "bottle": "Bottle",
    "box": "Box",
    "boxes": "Box",
    "btl": "Bottle",
    "bus": "Bus",
    "c grade": "Grade C",
    "c&f": "CNF",
    "calcutta": "Kolkata",
    "canceld": "Cancelled",
    "canceled": "Cancelled",
    "cancelled": "Cancelled",
    "carton": "Carton",
    "cash": "Cash",
    "casual leave": "Casual Leave",
    "cat": "Category",
    "category": "Category",
    "cawnpore": "Kanpur",
    "cc": "Credit Card",
    "cgst": "CGST",
    "chandigarh": "Chandigarh",
    "chattisgarh": "Chhattisgarh",
    "check": "Cheque",
    "chennai": "Chennai",
    "cheque": "Cheque",
    "chhatisgarh": "Chhattisgarh",
    "chhattisgarh": "Chhattisgarh",
    "cl": "Casual Leave",
    "clearing and forwarding": "CNF",
    "client": "Customer",
    "closed": "Closed",
    "cnf": "CNF",
    "cntct": "Contact",
    "cntrct": "Contract",
    "cochin": "Kochi",
    "coimbatore": "Coimbatore",
    "comp off": "Compensatory Off",
    "compensatory off": "Compensatory Off",
    "completd": "Completed",
    "completed": "Completed",
    "complt": "Completed",
    "cons": "Consumable",
    "consumable": "Consumable",
    "contact": "Contact",
    "container": "Container",
    "contract": "Contract",
    "correction": "Correction",
    "cr": "Credit",
    "credit": "Credit",
    "credit 90": "Credit 90",
    "credit card": "Credit Card",
    "credit90": "Credit 90",
    "crnt": "Current",
    "ctgry": "Category",
    "ctn": "Carton",
    "cuddapah": "Kadapa",
    "curr": "Current",
    "current": "Current",
    "cust": "Customer",
    "customer": "Customer",
    "daily": "Daily",
    "damage": "Damaged",
    "damage write off": "Damage Write Off",
    "damaged": "Damaged",
    "daman and diu": "Daman and Diu",
    "davangere": "Davangere",
    "dc": "Debit Card",
    "dd": "Demand Draft",
    "dealer": "Dealer",
    "debit": "Debit",
    "debit card": "Debit Card",
    "defective": "Defective",
    "dehra dun": "Dehradun",
    "dehradun": "Dehradun",
    "delhi": "Delhi",
    "delivered": "Delivered",
    "delivery": "Delivery",
    "delivrd": "Delivered",
    "delivry": "Delivery",
    "delv": "Delivery",
    "demand draft": "Demand Draft",
    "depart": "Department",
    "department": "Department",
    "dept": "Department",
    "desig": "Designation",
    "designation": "Designation",
    "dhanbad": "Dhanbad",
    "dist": "Distributor",
    "distributor": "Distributor",
    "divorced": "Divorced",
    "dlr": "Dealer",
    "dr": "Debit",
    "draft": "Draft",
    "drum": "Drum",
    "due": "Due",
    "dwarka": "Dwarka",
    "earned leave": "Earned Leave",
    "el": "Earned Leave",
    "empl": "Employee",
    "employe": "Employee",
    "employee": "Employee",
    "en route": "In Transit",
    "equity": "Equity",
    "erode": "Erode",
    "exempt": "Exempt",
    "exmpt": "Exempt",
    "expense": "Expense",
    "expenses": "Expense",
    "expired": "Expired",
    "expiry": "Expiry",
    "f": "Female",
    "fail": "Fail",
    "failed": "Fail",
    "false": "No",
    "faridabad": "Faridabad",
    "female": "Female",
    "fg": "Finished Good",
    "filed": "Filed",
    "finished good": "Finished Good",
    "finished goods": "Finished Good",
    "gauhati": "Guwahati",
    "goa": "Goa",
    "google pay": "UPI",
    "gorakhpur": "Gorakhpur",
    "gpay": "UPI",
    "grade a": "Grade A",
    "grade b": "Grade B",
    "grade c": "Grade C",
    "gst": "GST",
    "gst 12": "GST 12%",
    "gst 18": "GST 18%",
    "gst 28": "GST 28%",
    "gst 5": "GST 5%",
    "gujarat": "Gujarat",
    "gujrat": "Gujarat",
    "gulbarga": "Gulbarga",
    "gurgaon": "Gurgaon",
    "gurugram": "Gurgaon",
    "guwahati": "Guwahati",
    "gwalior": "Gwalior",
    "hajipur": "Hajipur",
    "half day": "Half Day",
    "half-day": "Half Day",
    "halfday": "Half Day",
    "haridwar": "Haridwar",
    "haryana": "Haryana",
    "himachal": "Himachal Pradesh",
    "himachal pradesh": "Himachal Pradesh",
    "hisar": "Hisar",
    "holiday": "Holiday",
    "hoshiarpur": "Hoshiarpur",
    "hourly": "Hourly",
    "hubballi": "Hubli",
    "hubli": "Hubli",
    "hyderabad": "Hyderabad",
    "igst": "IGST",
    "immediate": "Immediate",
    "imps": "IMPS",
    "in progress": "In Progress",
    "in transit": "In Transit",
    "in-progress": "In Progress",
    "inactive": "Inactive",
    "inactv": "Inactive",
    "income": "Income",
    "incorrect item": "Wrong Item",
    "indore": "Indore",
    "inprogress": "In Progress",
    "intern": "Intern",
    "intransit": "In Transit",
    "inv": "Invoice",
    "invc": "Invoice",
    "invoice": "Invoice",
    "jaipur": "Jaipur",
    "jalandhar": "Jalandhar",
    "jammu and kashmir": "Jammu and Kashmir",
    "jamnagar": "Jamnagar",
    "jamshedpur": "Jamshedpur",
    "jhansi": "Jhansi",
    "jharkhand": "Jharkhand",
    "jodhpur": "Jodhpur",
    "kadapa": "Kadapa",
    "kakinada": "Kakinada",
    "kalaburagi": "Gulbarga",
    "kanpur": "Kanpur",
    "kapurthala": "Kapurthala",
    "karnal": "Karnal",
    "karnatak": "Karnataka",
    "karnataka": "Karnataka",
    "karwar": "Karwar",
    "kashi": "Varanasi",
    "kerala": "Kerala",
    "kg": "KG",
    "kgs": "KG",
    "kilogram": "KG",
    "kochi": "Kochi",
    "kolhapur": "Kolhapur",
    "kolkata": "Kolkata",
    "kota": "Kota",
    "kovai": "Coimbatore",
    "kurnool": "Kurnool",
    "l": "Litre",
    "ladakh": "Ladakh",
    "late": "Late",
    "liabilities": "Liability",
    "liability": "Liability",
    "liter": "Litre",
    "litre": "Litre",
    "lop": "Loss of Pay",
    "lorry": "Lorry",
    "loss of pay": "Loss of Pay",
    "ltr": "Litre",
    "lts": "Litre",
    "lucknow": "Lucknow",
    "lucnow": "Lucknow",
    "ludhiana": "Ludhiana",
    "m": "Male",
    "madhya pradesh": "Madhya Pradesh",
    "madras": "Chennai",
    "madurai": "Madurai",
    "maharashtra": "Maharashtra",
    "maharastra": "Maharashtra",
    "maint": "Maintenance",
    "maintainence": "Maintenance",
    "maintenance": "Maintenance",
    "male": "Male",
    "mangalore": "Mangalore",
    "mangaluru": "Mangalore",
    "manipur": "Manipur",
    "manufacturer": "Manufacturer",
    "married": "Married",
    "maternity leave": "Maternity Leave",
    "mathura": "Mathura",
    "meerut": "Meerut",
    "meghalaya": "Meghalaya",
    "meter": "Meter",
    "metric ton": "MT",
    "mfr": "Manufacturer",
    "mini": "Mini Truck",
    "mini truck": "Mini Truck",
    "mizoram": "Mizoram",
    "ml": "Maternity Leave",
    "mohali": "Mohali",
    "monthly": "Monthly",
    "mount abu": "Mount Abu",
    "mp": "Madhya Pradesh",
    "mt": "MT",
    "mtr": "Meter",
    "mumbai": "Mumbai",
    "muzaffarpur": "Muzaffarpur",
    "mysore": "Mysore",
    "mysuru": "Mysore",
    "n": "No",
    "nagaland": "Nagaland",
    "nagpur": "Nagpur",
    "nalgonda": "Nalgonda",
    "nashik": "Nashik",
    "nasik": "Nashik",
    "neft": "NEFT",
    "nellore": "Nellore",
    "net 15": "Net 15",
    "net 30": "Net 30",
    "net 45": "Net 45",
    "net 60": "Net 60",
    "net15": "Net 15",
    "net30": "Net 30",
    "net45": "Net 45",
    "net60": "Net 60",
    "new delhi": "Delhi",
    "nil": "Nil Rated",
    "nil rated": "Nil Rated",
    "no": "Number",
    "no longer needed": "Not Required",
    "noida": "Noida",
    "not filed": "Not Filed",
    "not paid": "Unpaid",
    "not required": "Not Required",
    "notice": "Notice Period",
    "notice period": "Notice Period",
    "num": "Number",
    "number": "Number",
    "o negative": "O-",
    "o positive": "O+",
    "o+": "O+",
    "o-": "O-",
    "odisha": "Odisha",
    "office": "Office",
    "on hold": "On Hold",
    "on leave": "On Leave",
    "ongole": "Ongole",
    "onhold": "On Hold",
    "onleave": "On Leave",
    "open": "Open",
    "org": "Organization",
    "organisation": "Organization",
    "organization": "Organization",
    "orissa": "Odisha",
    "other": "Other",
    "over due": "Overdue",
    "overall": "Overall",
    "overdue": "Overdue",
    "packet": "Packet",
    "paid": "Paid",
    "panaji": "Goa",
    "panipat": "Panipat",
    "panjim": "Goa",
    "pass": "Pass",
    "passed": "Pass",
    "paternity leave": "Paternity Leave",
    "pathankot": "Pathankot",
    "patiala": "Patiala",
    "patna": "Patna",
    "payable": "Payable",
    "payble": "Payable",
    "pc": "Piece",
    "pcs": "Piece",
    "pend": "Pending",
    "pend approval": "Pending Approval",
    "pending": "Pending",
    "pending approval": "Pending Approval",
    "pending filing": "Pending Filing",
    "pending inspection": "Pending Inspection",
    "pendng": "Pending",
    "perm": "Permanent",
    "permanent": "Permanent",
    "phonepe": "UPI",
    "physical count variance": "Physical Count Variance",
    "pickup": "Pickup",
    "piece": "Piece",
    "pieces": "Piece",
    "pkt": "Packet",
    "pl": "Earned Leave",
    "planned": "Planned",
    "pondicherry": "Puducherry",
    "poona": "Pune",
    "prayagraj": "Prayagraj",
    "prchase": "Purchase",
    "prem": "Premium",
    "premium": "Premium",
    "present": "Present",
    "prev": "Previous",
    "previous": "Previous",
    "price": "Price",
    "privilege leave": "Earned Leave",
    "probation": "Probation",
    "probtn": "Probation",
    "prod": "Product",
    "product": "Product",
    "prsnt": "Present",
    "puducherry": "Puducherry",
    "pune": "Pune",
    "punjab": "Punjab",
    "purchase": "Purchase",
    "purchse": "Purchase",
    "qty": "Quantity",
    "quality": "Quality",
    "quality issue": "Quality Issue",
    "quantity": "Quantity",
    "quntity": "Quantity",
    "raipur": "Raipur",
    "rajahmundry": "Rajahmundry",
    "rajasthan": "Rajasthan",
    "rajkot": "Rajkot",
    "ranchi": "Ranchi",
    "raw": "Raw Material",
    "raw material": "Raw Material",
    "receivable": "Receivable",
    "received": "Received",
    "recievable": "Receivable",
    "recvd": "Received",
    "reg": "Register",
    "regd": "Registered",
    "register": "Register",
    "registered": "Registered",
    "rejctd": "Rejected",
    "rejected": "Rejected",
    "resolved": "Resolved",
    "retailer": "Retailer",
    "return to vendor": "Return to Vendor",
    "revenue": "Income",
    "rgstr": "Register",
    "rishikesh": "Rishikesh",
    "rohtak": "Rohtak",
    "roll": "Roll",
    "rtgs": "RTGS",
    "salem": "Salem",
    "secunderabad": "Hyderabad",
    "sent": "Sent",
    "serv": "Service",
    "service": "Service",
    "sgst": "SGST",
    "shimla": "Shimla",
    "shimoga": "Shimoga",
    "ship": "Shipping",
    "shipping": "Shipping",
    "shivamogga": "Shimoga",
    "short quantity": "Short Quantity",
    "shortage": "Short Quantity",
    "sick leave": "Sick Leave",
    "sikar": "Sikar",
    "sikkim": "Sikkim",
    "siliguri": "Siliguri",
    "single": "Single",
    "sl": "Sick Leave",
    "smry": "Summary",
    "solapur": "Solapur",
    "sonipat": "Sonipat",
    "sq ft": "Sq Ft",
    "sqft": "Sq Ft",
    "square feet": "Sq Ft",
    "srinagar": "Srinagar",
    "standard": "Standard",
    "std": "Standard",
    "stolen": "Theft",
    "submitted": "Submitted",
    "submtd": "Submitted",
    "summ": "Summary",
    "summary": "Summary",
    "superior": "Superior",
    "supplier": "Vendor",
    "surat": "Surat",
    "tamil nadu": "Tamil Nadu",
    "tamilnadu": "Tamil Nadu",
    "tata ace": "Tempo",
    "telangana": "Telangana",
    "telingana": "Telangana",
    "temp": "Temporary",
    "tempo": "Tempo",
    "temporary": "Temporary",
    "thane": "Thane",
    "theft": "Theft",
    "thiruvananthapuram": "Thiruvananthapuram",
    "tiruchirappalli": "Tiruchirappalli",
    "tirunelveli": "Tirunelveli",
    "tirupur": "Tirupur",
    "tiruvananthapuram": "Thiruvananthapuram",
    "ton": "MT",
    "tonne": "MT",
    "total": "Total",
    "totl": "Total",
    "tractor": "Tractor",
    "trading": "Trading",
    "trailer": "Container",
    "transport": "Transport",
    "transporter": "Transporter",
    "transportr": "Transporter",
    "transprt": "Transport",
    "trichy": "Tiruchirappalli",
    "tripura": "Tripura",
    "trivandrum": "Thiruvananthapuram",
    "truck": "Truck",
    "true": "Yes",
    "udaipur": "Udaipur",
    "udupi": "Udupi",
    "ujjain": "Ujjain",
    "unpaid": "Unpaid Leave",
    "unpaid leave": "Unpaid Leave",
    "up": "Uttar Pradesh",
    "upi": "UPI",
    "uttar pradesh": "Uttar Pradesh",
    "uttarakhand": "Uttarakhand",
    "uttaranchal": "Uttarakhand",
    "vadodara": "Vadodara",
    "van": "Van",
    "varanasi": "Varanasi",
    "vellore": "Vellore",
    "vendor": "Vendor",
    "verifd": "Verified",
    "verified": "Verified",
    "vijayawada": "Vijayawada",
    "visakhapatnam": "Visakhapatnam",
    "vizag": "Visakhapatnam",
    "vndr": "Vendor",
    "warangal": "Warangal",
    "warehous": "Warehouse",
    "warehouse": "Warehouse",
    "weekly": "Weekly",
    "west bengal": "West Bengal",
    "wh": "Warehouse",
    "wholesaler": "Wholesaler",
    "widowed": "Widowed",
    "wrong item": "Wrong Item",
    "y": "Yes",
    "yes": "Yes",
    "zero rated": "Nil Rated",
}


ENUM_VALUES = {
    "dim_OrgType.orgTypeCode": ["DLR", "DST", "VND", "SUP", "CNF", "TRP", "CUS", "MFR", "RTL", "WHL"],
    "dim_OrgType.orgTypeName": ["Dealer", "Distributor", "Vendor", "Supplier", "CNF", "Transporter", "Customer", "Manufacturer", "Retailer", "Wholesaler", "Agent", "Broker", "Consignee", "Consignor"],
    "dim_PaymentTerm.termName": ["Net 30", "Net 60", "Net 45", "Net 15", "Immediate", "Credit 90", "Advance"],
    "dim_Status.statusCategory": ["Order", "Invoice", "Delivery", "Payment", "Approval", "Leave", "Trip", "Purchase", "General", "Quality"],
    "dim_Status.statusCode": ["PEND", "APPR", "REJ", "CAN", "COMP", "INPR", "DRF", "SUB", "PAID", "UNPD", "OVER", "HOLD", "CLSD", "ACT", "INACT", "SENT", "RECV", "VER", "RES", "OPEN"],
    "dim_Status.statusName": ["Pending", "Approved", "Rejected", "Cancelled", "Completed", "In Progress", "Draft", "Submitted", "Paid", "Unpaid", "Overdue", "On Hold", "Closed", "Active", "Inactive", "Sent", "Received", "Verified", "Resolved", "Open"],
    "dim_TaxRate.taxName": ["GST 5%", "GST 12%", "GST 18%", "GST 28%", "Nil Rated", "Exempt"],
    "dim_TaxRate.taxType": ["SGST", "CGST", "IGST"],
    "dim_UOM.uomCode": ["KG", "MT", "LTR", "PCS", "BOX", "PKT", "BTL", "BAG", "DRM", "CTN", "ROL", "MTR", "SFT"],
    "dim_UOM.uomName": ["KG", "MT", "Litre", "Piece", "Box", "Packet", "Bottle", "Bag", "Drum", "Carton", "Roll", "Meter", "Sq Ft"],
    "dmn_Country.countryName": ["India"],
    "tbl_AccountGroup.groupType": ["Asset", "Liability", "Income", "Expense", "Equity"],
    "tbl_Attendance.status": ["Present", "Absent", "Half Day", "Late", "On Leave", "Holiday"],
    "tbl_CreditDebitNote.noteType": ["Credit", "Debit"],
    "tbl_Employee.bloodGroup": ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"],
    "tbl_Employee.employmentType": ["Permanent", "Contract", "Probation", "Intern", "Temporary", "Notice Period"],
    "tbl_Employee.gender": ["Male", "Female", "Other"],
    "tbl_Employee.maritalStatus": ["Single", "Married", "Divorced", "Widowed"],
    "tbl_GSTReturn.returnType": ["GSTR-1", "GSTR-3B"],
    "tbl_InventoryAdjustment.reason": ["Damage Write Off", "Theft", "Expiry", "Correction", "Physical Count Variance", "Return to Vendor"],
    "tbl_LeaveType.leaveCode": ["CL", "SL", "EL", "ML", "PL", "CO", "LOP", "UL"],
    "tbl_LeaveType.leaveName": ["Casual Leave", "Sick Leave", "Earned Leave", "Maternity Leave", "Paternity Leave", "Compensatory Off", "Loss of Pay", "Unpaid Leave"],
    "tbl_OrgAddress.addressType": ["Billing", "Shipping", "Registered", "Office"],
    "tbl_PaymentMade.paymentMode": ["NEFT", "RTGS", "Cheque", "Cash", "UPI", "IMPS", "Demand Draft", "Bank Transfer"],
    "tbl_PaymentReceived.paymentMode": ["NEFT", "RTGS", "Cheque", "Cash", "UPI", "IMPS", "Demand Draft", "Bank Transfer"],
    "tbl_PayrollHeader.payMonth": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    "tbl_ProductCategory.categoryName": ["Raw Material", "Finished Good", "Consumable", "Trading", "Service"],
    "tbl_ProductGrade.gradeName": ["Grade A", "Grade B", "Grade C", "Premium", "Standard"],
    "tbl_ProductMaster.brand": ["Brand A", "Brand B", "Brand C", "Premium Brand"],
    "tbl_QualityTestResult.result": ["Pass", "Fail"],
    "tbl_SaleReturn.returnReason": ["Damaged", "Expired", "Wrong Item", "Defective", "Not Required", "Quality Issue", "Short Quantity"],
    "tbl_TDSDeduction.tdsSection": ["194A", "194C", "194H", "194I", "194J", "194Q"],
    "tbl_TripSheet.tripStatus": ["Planned", "In Transit", "Delivered", "Cancelled"],
    "tbl_UserMaster.role": ["Admin", "Manager", "Supervisor", "User", "Viewer", "Accountant", "Sales Executive", "Purchase Executive"],
    "tbl_VehicleMaster.vehicleType": ["Truck", "Lorry", "Tempo", "Container", "Pickup", "Van", "Mini Truck"],
}


BUSINESS_TERMS = {
    "AP": "Accounts Payable - Money the company owes to vendors for goods or services received",
    "AR": "Accounts Receivable - Money owed to the company by customers for goods or services delivered",
    "BOM": "Bill of Materials - List of raw materials, components, and quantities needed to manufacture a product",
    "BS": "Balance Sheet - Financial statement summarizing assets, liabilities, and equity",
    "CGST": "Central Goods and Services Tax - Central-level component of GST on intra-state transactions",
    "CNF": "C&F Agent (Clearing and Forwarding Agent) - Logistics intermediary for clearance and forwarding",
    "COGS": "Cost of Goods Sold - Direct costs attributable to the production of goods sold",
    "CST": "Central Sales Tax - Tax on inter-state sales (largely subsumed under GST)",
    "DA": "Dearness Allowance - Allowance paid to employees to offset cost of living increases",
    "DSA": "Daily Sales Analysis - Report analyzing daily sales performance and trends",
    "E-Way Bill": "Electronic Way Bill - Document required for movement of goods above INR 50,000",
    "EBITDA": "Earnings Before Interest, Taxes, Depreciation, and Amortization",
    "EOQ": "Economic Order Quantity - Optimal order quantity minimizing total inventory costs",
    "ESI": "Employee State Insurance - Self-financing social security and health insurance scheme",
    "FIFO": "First In First Out - Inventory valuation method assuming oldest items are sold first",
    "GL": "General Ledger - Complete record of all financial transactions over the life of a company",
    "GR": "Goods Receipt - Process of receiving goods from a supplier and recording into inventory",
    "GRN": "Goods Receipt Note - A document acknowledging receipt of goods from a supplier",
    "GST": "Goods and Services Tax - Comprehensive, multi-stage, destination-based indirect tax",
    "GSTIN": "Goods and Services Tax Identification Number - Unique 15-digit alphanumeric ID for GST-registered taxpayers",
    "GSTR-1": "GST Return 1 - Monthly/quarterly return for outward supplies of goods or services",
    "GSTR-3B": "GST Return 3B - Monthly summary return for outward supplies and input tax credit",
    "GTA": "Goods Transport Agency - Transporter registered under GST for goods transport services",
    "HRA": "House Rent Allowance - Salary component for rental accommodation expenses",
    "HSN": "Harmonized System of Nomenclature - Standardized system for classifying traded products",
    "HSN Code": "Harmonized System of Nomenclature Code - Standardized product classification code",
    "IFSC": "Indian Financial System Code - Alphanumeric code used to identify bank branches for electronic transfers",
    "IGST": "Integrated Goods and Services Tax - GST component on inter-state transactions",
    "IMPS": "Immediate Payment Service - Instant interbank electronic fund transfer service",
    "INR": "Indian Rupee - The official currency of India",
    "ISD": "Input Service Distributor - Office distributing input tax credit to branches",
    "ITC": "Input Tax Credit - Credit for GST paid on inputs available against output GST liability",
    "JV": "Journal Voucher - Document recording a financial journal entry with debit/credit pairs",
    "KPI": "Key Performance Indicator - Measurable value demonstrating effectiveness in achieving objectives",
    "LIFO": "Last In First Out - Inventory valuation method assuming newest items are sold first",
    "LR": "Lorry Receipt - Receipt issued by a transporter acknowledging receipt of goods",
    "MICR": "Magnetic Ink Character Recognition - Code printed on cheques for clearing and routing",
    "MIS": "Management Information System - Reports providing information for managerial decision-making",
    "MRP": "Maximum Retail Price - Highest price that can be charged for a product",
    "NEFT": "National Electronic Funds Transfer - Electronic fund transfer system for bank-to-bank transfers",
    "Outstanding": "Outstanding Amount - Amount yet to be paid by a customer or to a vendor",
    "P&L": "Profit and Loss Statement - Financial statement summarizing revenues, costs, and expenses",
    "PAN": "Permanent Account Number - Unique 10-character alphanumeric identifier issued by Income Tax Department",
    "PF": "Provident Fund - Retirement benefit scheme managed by EPFO",
    "PO": "Purchase Order - Commercial document issued to a seller indicating type, quantity, and agreed price",
    "POS": "Point of Sale - Location where a retail transaction is completed",
    "PT": "Professional Tax - State-level tax on employment income",
    "QC": "Quality Control - Process of ensuring product quality meets specified standards",
    "RC": "Registration Certificate - Document certifying vehicle registration with transport authority",
    "RCM": "Reverse Charge Mechanism - GST payment mechanism where recipient pays tax instead of supplier",
    "RFQ": "Request for Quotation - Document soliciting price quotes from potential vendors",
    "ROI": "Return on Investment - Measure of profitability relative to investment cost",
    "RTGS": "Real Time Gross Settlement - Continuous real-time settlement of fund transfers individually",
    "SAC": "Service Accounting Code - Code for classifying services under GST",
    "SGST": "State Goods and Services Tax - State-level component of GST on intra-state transactions",
    "SKU": "Stock Keeping Unit - Unique identifier for each distinct product and service that can be purchased",
    "SO": "Sales Order - Commercial document confirming the sale of products or services",
    "TA": "Travel Allowance - Allowance for travel-related expenses for employees",
    "TCS": "Tax Collected at Source - Tax collected by seller from buyer on specified transactions",
    "TDS": "Tax Deducted at Source - Withholding tax deducted on payments as per Income Tax Act",
    "TP": "Trip Sheet - Document recording transportation trip details including vehicle, driver, and route",
    "UOM": "Unit of Measurement - Standard unit used to measure quantity of products",
    "UPI": "Unified Payments Interface - Real-time payment system facilitating inter-bank transactions via mobile",
    "VAT": "Value Added Tax - Pre-GST indirect tax system (replaced by GST in India)",
    "WIP": "Work in Progress - Partially finished goods awaiting completion",
}


SUCCESSFUL_QUERIES = [
    "how many products",
    "count of employees",
    "total sales amount",
    "total purchase orders this month",
    "average salary",
    "list all customers",
    "show active products",
    "list all brands",
    "show all invoices",
    "list suppliers",
    "total sales by product",
    "sale orders with customer name",
    "attendance with department",
    "invoices with line items",
    "products with category",
    "employee details with designation",
    "stock ledger with product details",
    "purchase orders with vendor name",
    "sale orders with product names and customer details",
    "invoices with product categories and tax breakdown",
    "purchase orders with supplier info and product details",
    "employee payroll with department and attendance",
    "stock transfers with product and warehouse details",
    "trip sheet with driver and vehicle details",
    "booking details with organization and product grade",
    "journal vouchers with account ledger and organization",
    "sales by region",
    "product profitability across sales and purchase",
    "employee sales performance",
    "organization compliance and financial standing",
    "quality test results for products sold",
    "show me inactive products",
    "list cities in Maharashtra",
    "total quantity of stock in warehouse",
    "pending deliveries for this month",
    "purchase enquiries this month",
    "total purchase invoices amount",
    "vendor evaluation scores",
    "physical inventory count",
    "stock adjustments this month",
    "credit notes issued",
    "payments made to vendors",
    "payments received from customers",
    "pending leave applications",
    "list leave types",
    "sale returns this month",
    "eway bills generated today",
    "product pricing list",
    "global purchase rates",
    "global sale rates",
    "pending rate approvals",
    "quality checklists",
    "quality parameters",
    "list all system users",
    "audit log today",
    "list all countries",
    "list all states",
    "list all units of measure",
    "list all tax rates",
    "list organization types",
    "list all statuses",
    "list payment terms",
    "error logs",
    "organization registrations",
    "purchase enquiries with vendor name",
    "purchase invoices with order reference",
    "vendor evaluation with vendor name",
    "physical inventory with warehouse details",
    "inventory adjustments with product details",
    "credit notes with invoice details",
    "payments made with vendor name",
    "payments received with customer name",
    "leave applications with employee details",
    "sale returns with invoice number",
    "eway bills with invoice details",
    "product pricing with product name",
    "global purchase rates with product details",
    "global sale rates with product details",
    "quality parameters with product details",
    "audit log with user name",
    "organization addresses with city",
    "organization bank details",
    "organization contacts list",
    "org registration details with organization name",
    "product categories with parent category",
    "routes with source and destination cities",
    "rate bands with global purchase rate",
    "purchase invoices with vendor and product details",
    "inventory adjustments with product and warehouse",
    "credit notes with invoices and customer info",
    "leave applications with employee and leave type",
    "sale returns with invoices and customer details",
    "eway bills with purchase schedules and status",
    "product pricing with product and grade",
    "quality test results with checklist and parameters",
    "user master with employee and department",
    "physical inventory count with product and warehouse",
    "booking delivery with booking and invoice",
    "purchase enquiries with product and vendor",
    "purchase invoices vs payments made",
    "inventory stock with product pricing",
    "employee leave and attendance summary",
    "eway bills with trip details",
    "quality test results for purchase materials",
    "vendor payments and compliance status",
    "user activity audit with employee info",
    "product master with gst rates and pricing",
    "organization contacts by city and state",
    "sale and purchase rate comparison by product",
    "loading details with trip and invoice info",
    "product categories with class and master",
    "booking delivery status with organization and grade",
    "tds deductions with invoices and organization",
    "payroll details with employee and department",
    "list all HSN codes for products",
    "show department names and codes",
    "list designation names with rank",
    "show product grades and their codes",
    "list product classes with category info",
    "show account groups by group type",
    "list account ledgers with opening balance",
    "show GST returns with outward and inward totals",
    "list error logs by severity level",
    "show system users with their roles",
    "list warehouse codes and names",
    "show attendance records with in time and out time",
    "list pay slip earnings breakdown",
    "show country names and country codes",
    "list product grade codes and names",
    "journal vouchers with ledger debits and credits",
    "GST returns with filing status",
    "stock transfers with source and destination warehouse",
    "product classes with their parent category",
    "error logs with system user info",
    "attendance records with employee full name",
    "payroll breakdown with earnings headers",
    "vehicle master with insurance expiry dates",
    "driver license and expiry details",
    "route details with source and destination city",
    "loading details with product and shipped quantity",
    "quality test results with parameter observed values",
    "TDS deductions with challan number and organization",
    "rate approvals with approver name and status",
    "sale order line items with product names",
    "GST returns with outward and inward totals by organization",
    "stock transfer with product, warehouse and transfer details",
    "journal vouchers with account group and organization",
    "attendance with employee department and designation",
    "trip sheet with driver vehicle and route details",
    "quality test results with parameter checklist and product",
    "loading details with trip product and warehouse",
    "payroll header with detail employee and department",
    "product master with grade class and category",
    "TDS deductions with sales invoices and GST returns",
    "system audit trail with error logs and user employee info",
    "booking deliveries with product grade and customer organization",
    "account groups and ledgers with organization compliance",
    "HR payroll and attendance with finance payments",
    "product pricing with quality parameters and test results",
    "inventory adjustments with logistics vehicle trips",
    "sales booking with purchase enquiries and product master",
    "organization bank details with payment transactions",
    "system user audit actions with error logs",
    "vehicle fitness and insurance status with trip history",
    "product grade pricing across global sale and purchase rates",
    "employee leave attendance and payroll summary",
    "list all payments made in the last financial year",
    "top 10 products by sales quantity",
    "show me duplicate invoice numbers",
    "show product categories with their parent categories",
    "rate bands with minimum and maximum quantity ranges",
    "list stock transfers with remarks and status",
    "organization contacts with phone and email designation",
]

TERMS_DATA = {
    "table_aliases": TABLE_ALIASES,
    "value_corrections": VALUE_CORRECTIONS,
    "enum_values": ENUM_VALUES,
    "business_terms": BUSINESS_TERMS,
    "successful_queries": SUCCESSFUL_QUERIES,
}
